### ISSUE TITLE
Frost appears/disappears between desert/desert oasis (custom biome to Terralith)

### ISSUE THREAD

**Issue by Macintosh-Fan** [X0nk/Bliss-Shader#105]
Might be tricky to implement, but is there a way to check custom biomes to see if they are similar to specified regular Minecraft biomes?

Desert
![desert](https://github.com/X0nk/Bliss-Shader/assets/50642934/4feb0928-6d74-409c-b8b9-7d9b681b1893)

Desert oasis
![desert_oasis](https://github.com/X0nk/Bliss-Shader/assets/50642934/a1ce10db-257b-4bdc-9653-b87481b58030)

**Comment by X0nk** [comment]
this is normal. i dont want stnow/rain puddles to exist in hot/dry biomes, this is the only way i can make that work
