### ISSUE TITLE
LOD chunks of DH covers the render-distance chunks

### ISSUE THREAD

**Issue by Edgillock** [X0nk/Bliss-Shader#107]
I'm running with a setup of Minecraft version 1.19.2 along with Optifine HD I2 Ultra, Forge 43.2.14 and DH 2.0.0a. It appears that those LOD chunks drawn by DH just obscure the field of view. Switching between the dev version of Bliss and the release version result the same, and deleting the .sqlite cache file generated by DH to reload the chunks wouldn't work either. Please see the screenshots attached. Thanks!
![2024-04-24_18 28 27](https://github.com/X0nk/Bliss-Shader/assets/160697574/242d8404-1fc2-4c39-ba7b-ed1fc2049995)
![2024-04-24_18 28 36](https://github.com/X0nk/Bliss-Shader/assets/160697574/550b58d2-7b0f-4f41-a4ac-6e2a379952e6)

**Comment by X0nk** [comment]
optifine does not support shaders with distant horizons. only the very latest iris does.
