### ISSUE TITLE
Tree shadows look bad and change when moving

### ISSUE THREAD

**Issue by EQQx110** [X0nk/Bliss-Shader#108]
I don't know much about graphics but this issue seems to be related to hardcoded SSS. It's not present in the latest release, just in the in-development version.

This is with SSS_view turned on (all other settings default):
![2024-04-26_22 58 25](https://github.com/X0nk/Bliss-Shader/assets/108895045/1d423654-933e-41c6-98a5-e2d6ae99b3a1)

This is with SSS Mode set on Harcoded only:
![2024-04-26_22 58 37](https://github.com/X0nk/Bliss-Shader/assets/108895045/b6355e5b-74d6-4f64-ab5b-1f5dfbabf660)

This is with SSS Mode set on LabSSS only:
![2024-04-26_22 58 45](https://github.com/X0nk/Bliss-Shader/assets/108895045/ed6aec33-be44-4450-be38-9153092ecf5d)

**Comment by X0nk** [comment]
ah yeah this is related to the new translucent shadows. if you turn those off it will stop the issue. shader settings -> direct light
fear not though, i have fixed this problem in the coming update.

**Comment by X0nk** [comment]
i have fixed this issue. please redownload
