### ISSUE TITLE
Everything under sky is turning dark while using Distant Horizons with Bliss Shader

### ISSUE THREAD

**Issue by venmq** [X0nk/Bliss-Shader#109]
![Base Profile Screenshot 2024 04 27 - 14 11 27 25](https://github.com/X0nk/Bliss-Shader/assets/168274579/dabecd26-ba62-4c9e-b8d5-872bce6e49d1)
If I turn the DH mod off everything is okay, but when i use it, everything becomes dark (caves and terrain). I'm using Forge+Optifine on 1.19.2

**Comment by X0nk** [comment]
go to the iris discord https://irisshaders.dev/

and follow the instructions. you CANNOT use distant horizons with shaders on anything but iris.
