### ISSUE TITLE
Blocks underwater with Distant Horizons looking bad

### ISSUE THREAD

**Issue by EQQx110** [X0nk/Bliss-Shader#112]
![2024-04-28_23 47 27](https://github.com/X0nk/Bliss-Shader/assets/108895045/61019a70-fd21-44f3-a187-8468f9828733)

![2024-04-29_00 11 12](https://github.com/X0nk/Bliss-Shader/assets/108895045/0eb16939-5a11-404c-b251-f590643d028d)

I know I'm opening a lot of issues but I love this shader, I really appreciate your work. Are you going to make updates to the weather? Thunderstorms don't feel much like a thunderstorm with so few clouds covering the sky.

**Comment by X0nk** [comment]
this is a limitation i have to get around for blending distant horizons water, its a known problem
