### ISSUE TITLE
Strange black round spots on glass with resourcepacks?

### ISSUE THREAD

**Issue by tp1415926535** [X0nk/Bliss-Shader#114]
# Base Mod
* fabric-api-0.97.0+1.20.4
* sodium-fabric-0.5.8+mc1.20.4
* iris-mc1.20.4-1.6.17

# Comparison
## Case 1
* Resourcepacks: patrix_1.20.4_32x_basic
* shaderpacks: current source (2024/4/28)
![2024-04-29_21 18 49](https://github.com/X0nk/Bliss-Shader/assets/58326584/ad863dc7-7e96-4f15-b5af-05bb6a88a7ae)
![demo](https://github.com/X0nk/Bliss-Shader/assets/58326584/af8a70d9-4306-4707-82f5-1b38eb035cd2)

## Case 2
* resourcepacks: patrix_1.20.4_32x_basic
* shaderpacks: bliss_v2.0.4_(Chocapic13_Shaders_edit)
![2024-04-29_21 19 09](https://github.com/X0nk/Bliss-Shader/assets/58326584/70d4c26d-82db-488c-bf48-370fa6c14446)

## Case 3
* resourcepacks: none
* shaderpacks: current source (2024/4/28)
![2024-04-29_21 21 13](https://github.com/X0nk/Bliss-Shader/assets/58326584/61264137-6ffb-481e-b19c-2b763b8e5c7f)

When I use option 1, I don't know how to get rid of this black circle. It looks like the current source code version has more incompatibilities than the previous official version.

**Comment by X0nk** [comment]
this will be fixed in the coming update
