### ISSUE TITLE
The light does not pass through the glass

### ISSUE THREAD

**Issue by Line1337** [X0nk/Bliss-Shader#115]
Hello, I built a building made of black glass and found that the light passes through it very poorly or does not pass at all, can you fix it? I used the latest version, which is under development.
![2024-05-01_19 53 26](https://github.com/X0nk/Bliss-Shader/assets/168666314/caafb486-6da7-48a4-98c9-37c5bf19258a)

**Comment by X0nk** [comment]
this should be fixed in the latest in-development verison
