### ISSUE TITLE
Max distance shadow = -1 chunks ?

### ISSUE THREAD

**Issue by tp1415926535** [X0nk/Bliss-Shader#120]
I'm using the latest dev version (2024/5/6) and the shadow setting is -1. The closer LODs look very strange, like they're translucent, while the farther LODs are ok.
![2024-05-08_19 55 17](https://github.com/X0nk/Bliss-Shader/assets/58326584/f33512c9-99f8-4685-8400-103effff3bd9)
![2024-05-08_19 56 57](https://github.com/X0nk/Bliss-Shader/assets/58326584/94c8d538-c4d7-495e-8988-9397118f2809)

Whereas in the dev version before the update (2024/4/28) it had a max shadow distance of 8 chunks and looked more normal.
![2024-05-08_19 54 19](https://github.com/X0nk/Bliss-Shader/assets/58326584/f52ae227-95f3-4d53-9271-a3b425054052)
![2024-05-08_19 57 44](https://github.com/X0nk/Bliss-Shader/assets/58326584/df04023b-d4a1-46a5-a0f6-cfff69d6f5bd)

**Comment by X0nk** [comment]
ah yeah im aware of this, its not a bug that it is -1, it was a setting i forgot to switch the changes off of.
go to `shader settings -> direct light -> max shadow bounds = optimized`
i also dont reccomend enabling the DH shadowmap option right now, as ive got some blending stuff to fix with it

**Comment by X0nk** [comment]
ive fixed this up, go redownload
