### ISSUE TITLE
Water surface leads to character transparency

### ISSUE THREAD

**Issue by tp1415926535** [X0nk/Bliss-Shader#122]
Development version (2024/5/9)
![2024-05-09_19 28 45](https://github.com/X0nk/Bliss-Shader/assets/58326584/86f6f4bd-50c4-4348-b875-ce5e6e10094a)
![2024-05-09_19 28 00](https://github.com/X0nk/Bliss-Shader/assets/58326584/e5036999-aaf6-4e69-bc6f-3c0efe0c38c9)

**Comment by X0nk** [comment]
this has been fixed, go re-download
