### ISSUE TITLE
Fish and squid brightly colored

### ISSUE THREAD

**Issue by willydee** [X0nk/Bliss-Shader#123]
Here's what fish look like when seen seen from above the water:
![Screenshot from 2024-05-09 19-01-48](https://github.com/X0nk/Bliss-Shader/assets/7428576/49289aa3-726b-49aa-ab28-5176431b59f7)

## Versions
- Minecraft 1.20.4 vanilla
- Fabric Loader 0.15.11
- Iris 1.7.0+mc1.20.4
- Sodium 0.5.8+mc1.20.4
- Bliss-Shader-main.zip downloaded on May 9, 2024

Nothing else modified, default shader config. Looks like a recent regression; it did not look like that in previous revisions.

**Comment by X0nk** [comment]
it will be very useful to know what kind of graphics drivers you have, as differences exist for linux AMD drivers vs windows AMD drivers.
on top of that, just knowing what operating system you're using works too.

**Comment by willydee** [comment]
Sure can do; sorry for giving incomplete information :blush: 

![2024-05-09_20 22 19](https://github.com/X0nk/Bliss-Shader/assets/7428576/e49e01db-c6d3-43cc-824c-86790bfb5a7c)

**Comment by willydee** [comment]
![image](https://github.com/X0nk/Bliss-Shader/assets/7428576/b2df6c16-3f9e-4ab1-94c6-9239ebeb9812)

**Comment by julianjarjour** [comment]
I have the same issue on Arch Linux.
![image](https://github.com/X0nk/Bliss-Shader/assets/79441385/6cb19ef6-f712-4fb6-8c9a-212edc3d7a7d)
It happens with probably every entity, here's a boat:
![2024-06-05_11 16 10](https://github.com/X0nk/Bliss-Shader/assets/79441385/b4847660-4bb8-4f3f-b098-4ed29de86598)
And it happens in the reverse, looking up from underwater:
![2024-06-05_11 16 30](https://github.com/X0nk/Bliss-Shader/assets/79441385/1940c159-a2a9-4205-9fcd-1e8c3875b2f2)

**Comment by willydee** [comment]
@julianjarjour I was tempted to blame it on an AMD driver update (since you also have an AMD GPU), but then, when I'm using an older Bliss main build (sorry, I have no idea which version or build that would be), these artifacts are not there, so it looks like a regression in Bliss.

I noticed the same effect when looking through glass: entities are brightly colored.

**Comment by X0nk** [comment]
i am still trying to determine what this issue is caused by.
i do not have any machine with linux with amd, i cant directly test it...
so far my best guess is related to writing to buffers/color attachments, and how different drivers will handle the situation

**Comment by willydee** [comment]
@X0nk I was able to test on my laptop, which is also running ArchLinux, but with an Intel GPU. It shows the same effect, so it is actually not an AMD-only problem. I don't have any other Linux distro at hand to try with.

**Comment by willydee** [comment]
Is there any way of determining which build/revision of Bliss-Shader-main I am actually running?

**Comment by Absolute-Potato** [comment]
Updating from the last version I had immediately fixed the problem (I only very quickly checked for like a minute, but beds and villagers stopped glowing through windows and thats good enough for me)

**Comment by julianjarjour** [comment]
All good now!
