### ISSUE TITLE
Deph of Field seems to be broken

### ISSUE THREAD

**Issue by DgtalCode** [X0nk/Bliss-Shader#124]
Hi,
On the pictures you can see that DoF setting is Off, but long-range objects are still blurry.
Tried turning a lot of other settings, and that blur is like static, nothing affects to that.
So, here are screenshots of a bug itself (is it a bug, idk, mb other settings), my setup and DoF settings window.

![2024-05-10_21 01 59](https://github.com/X0nk/Bliss-Shader/assets/32205408/2e538798-7194-4512-9625-d5418589201a)
![2024-05-10_21 02 11](https://github.com/X0nk/Bliss-Shader/assets/32205408/1b7dff0b-3bfd-4b60-8114-051bab7629fa)
![2024-05-10_21 03 01](https://github.com/X0nk/Bliss-Shader/assets/32205408/bf36b08d-bbe8-46e5-a73b-82bd97654ad3)

Versions:
* Minecraft: 1.20.5
* version of a shader: 8c5c26abde9aad26feffe3e28206a938803cdb0e commit
* Fabric + Iris 1.20.5

**Comment by X0nk** [comment]
this is bloomy fog, not a bug. you can configure it in fog settings
