### ISSUE TITLE
Bliss Dev With distant horizons through IRIS

### ISSUE THREAD

**Issue by BobbyHemming** [X0nk/Bliss-Shader#126]
Mac M1 - Minecraft 1.20.4

composite2: composite2: WARNING: Could not find vertex shader attribute 'at_tangent' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'mc_midTexCoord' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'UV0' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'iris_Entity' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'at_midBlock' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'mc_Entity' to match BindAttributeLocation request.
WARNING: Output of vertex shader 'iris_FogFragCoord' not read by fragment shader
WARNING: Output of vertex shader 'zMults' not read by fragment shader
ERROR: Implementation limit of 16 active fragment shader samplers (e.g., maximum number of supported image units) exceeded, fragment shader uses 19 samplers

**Comment by chair-man-f** [comment]
distant horizons + bliss do not work on m1 macs at the moment

**Comment by chair-man-f** [comment]
you can try this tho

https://github.com/lilac-eclipse/Bliss-Shader/releases/tag/mac-compat-pre-0.0.1
