### ISSUE TITLE
Glass with giant dark shadow orb in the middle

### ISSUE THREAD

**Issue by AEPhoenixz** [X0nk/Bliss-Shader#127]
Theres a giant shadow orb when using patrix x32 texture pack. this visual bug can be mediated by turning off specular reflections for water, But doing so will darken the glass by around 40% making it darker than black stained glass. also all stained variants do not have this orb or darkening issue only non-stained glass has this.

just making this heard to see if it could be fixed.

![2024-05-13_22 44 18](https://github.com/X0nk/Bliss-Shader/assets/169740123/b1b35f8e-c084-40b5-8593-68d262627ea8)

**Comment by X0nk** [comment]
update to the latest in-development version, as i have fixed this issue
