### ISSUE TITLE
Candle lights don't glow, only the candle itself

### ISSUE THREAD

**Issue by churchner420** [X0nk/Bliss-Shader#13]
Candles don't work like torches. Logically, the flame should glow but not the candle itself. Though the candles itself glows but not the flame (looks odd)

**Comment by X0nk** [comment]
that is exactly what it did before you opened the first issue. so i will just revert it back to this.
![image](https://github.com/X0nk/Bliss-Shader/assets/122314734/2f1863c7-3972-4f86-9589-dd80bf2fa2da)

the flame _does_ glow. it glows at the brightness of the highest torch light level.

**Comment by churchner420** [comment]
> that is exactly what it did before you opened the first issue. so i will just revert it back to this. ![image](https://user-images.githubusercontent.com/122314734/254046143-2f1863c7-3972-4f86-9589-dd80bf2fa2da.png)
> 
> the flame _does_ glow. it glows at the brightness of the highest torch light level.

Yep, just noticed it myself, thanks for reverting back to the old method. Though as you can see at this picture, a single candle barely lights up the scene at all and the glow only becomes quite realistic when adding 4 torches. All other candle numbers (3 or lower) on a single block are extremely dark. Is there a way to increase the glow amount and the amount of light the torchs adds to the surrounding scene without adding it to the light list?

![2023-07-17_21 40 29](https://github.com/X0nk/Bliss-Shader/assets/18448228/e0963322-238f-4da4-80ba-468e814c67db)

**Comment by X0nk** [comment]
as i said before, i cannot control how much light comes out from any blocks, i can only control the gradient of the light.
i also cannot do a special gradient for different blocks, they all have one single gradient. i cannot change this. this is how vanilla minecraft does its lighting.

with that in mind, please realize that a single candle seemingly gives off almost no light even in vanilla, without a shader, in a similar scenario to your screenshot.
![image](https://github.com/X0nk/Bliss-Shader/assets/122314734/9c0b2a4e-0ae3-4654-be5d-1b4aea65e78c)

**Comment by churchner420** [comment]
Okay, since there is no way I accept it as it is, thanks for having a look into it. And I have to say that the candles look really nice. Though I have commented your commit where you added the glow multiplier in gbuffers_all_particles.fsh. I have tried a couple of numbers and 5.0 looks really realistic

**Comment by X0nk** [comment]
i can add an adjustable setting just for that, but im pretty satisfied with 2.0. on top of that, i will probably make it also scale with the emissive brightness multiplier

**Comment by churchner420** [comment]
Oh yes that's a really good idea. Though I really like the brughtness and glow of the torches. I don't think it would make much sense if you added one slider for every emitter since just the candles need adjustments. So I think an adjustable slider for just the candles would do and maybe some seperate ones for other emitters.

And since we're talking about sliders, here is another suggestion:
In composite1.fsh line 355 (water caustics code) I added a multiplier for the water caustics brightness cause in my opinion they do look realitic but are way too dark (compared with real-life caustics and for example the ones from the Seus Shader).

**Comment by churchner420** [comment]
Okay, then I'd be fine with an intensity slider for the particles as a whole. 

For the water caustics, yes, a brightness slider would help out there. Looking forward to it :)

Discord is a good suggestion in general, I just sent you a request. Though I will probably be more active on Github to watch the progress with the shader than on Discord
