### ISSUE TITLE
Weird Screen Space Reflections

### ISSUE THREAD

**Issue by 19PHOBOSS98** [X0nk/Bliss-Shader#131]
Hello! I got the latest in dev build from github. I enabled  Specular Reflections and Screen-Space Reflections. When I tried looking at some gold blocks, I saw my own literal screen reflection:
![2024-05-20_08 45 52](https://github.com/X0nk/Bliss-Shader/assets/37253663/c822e5e8-8163-4fe8-9a3d-e9f50c7519e3)
![2024-05-20_08 46 09](https://github.com/X0nk/Bliss-Shader/assets/37253663/47e4ccad-9b05-4c2a-b176-9f88f70b2408)

![2024-05-20_08 51 09](https://github.com/X0nk/Bliss-Shader/assets/37253663/c85342b9-3506-4d36-a8b8-950ec92a7e02)

**Comment by X0nk** [comment]
yeah. that happens sometimes. its been there since the beginning of bliss, havent ever figured it out
