### ISSUE TITLE
Game crashes when entering nether or the end dimension (Apple Silicon)

### ISSUE THREAD

**Issue by gabrielchoong** [X0nk/Bliss-Shader#132]
Hi, I'm playing around with shaders and I found that Bliss-Shader V2 will crash your game if you either activate the Bliss Shader before or after entering a new dimension (Regardless of the Nether or The End). I am running on macOS 14.5 on the M1 processor.

I know that shaders aren't prioritised for Apple devices, so not hoping for a fix.

**Comment by X0nk** [comment]
is "Bliss-Shader V2" the exact name? because that is not a version i have ever listed.

**Comment by GroxDots** [comment]
That was a bug in curseforge/modrinth versions. It is fixed in the index versions.

**Comment by X0nk** [comment]
oke
