### ISSUE TITLE
无法正常加载

### ISSUE THREAD

**Issue by S-1-5-21-1726115** [X0nk/Bliss-Shader#133]
无法正常加载：
composite1.fsh: composite1.fsh: ERROR: 0:334: 'waterVolumetrics' : no matching overloaded function found (using implicit conversion) 
ERROR: 0:334: 'waterVolumetrics' : function is not known 
![屏幕截图 2024-05-22 220614](https://github.com/X0nk/Bliss-Shader/assets/151151280/a23e2581-2137-4ba3-872d-136606bd38cc)

**Comment by X0nk** [comment]
this has been fixed since then. download the latest in-development verison
