### ISSUE TITLE
Armor transparent in third person

### ISSUE THREAD

**Issue by SerShef** [X0nk/Bliss-Shader#136]
Here are some examples with the latest development branch, vanilla, and the latest stable...

![2024-05-25_01 23 43](https://github.com/X0nk/Bliss-Shader/assets/170794700/63007a63-3395-404b-ac77-c3ef67b3a02a)
![2024-05-25_01 23 57](https://github.com/X0nk/Bliss-Shader/assets/170794700/41f2897b-13f0-489c-908b-0e36d5061a19)
![2024-05-25_01 24 07](https://github.com/X0nk/Bliss-Shader/assets/170794700/3770809a-2a7e-4279-b85d-05657dad598f)

Looks like some kind of rendering error... It only applies to my armor and cape, my skin is opaque.

**Comment by X0nk** [comment]
this is caused by a mod that alters the third person view of the player. i cannot fix this.

**Comment by Pikmingaming9382** [comment]
hey, @X0nk, I also have this issue, and I was wondering, do you know what kind of "_mods that alters the third person view of the player_" causes this to happen, so I could delete the mod and fix the problem?
Thanks,
_William_

**Comment by X0nk** [comment]
shoulder surfing reloaded is a common one

**Comment by ShadersDreams** [comment]
Hey, on Bliss it worked for me by just turning off TRANSLUCENT_ENTITIES in DEBUGING/Experimental settings, thank you for this features X0nk!

**Comment by wtf8hz4rj2-max** [comment]
<img width="1920" height="982" alt="Image" src="https://github.com/user-attachments/assets/5b6a8e2c-c5a8-47ec-b2bf-340897f1c06b" />

yo tengo este problema con unos shaders que se llaman Erbium/copia de los pothon pero ya asi viene con ese bug y no se como solucionarlo, alguien que me ayude a solucionarlo no se si sea algun error de codigo o algo de compatibilidad

**Comment by X0nk** [comment]
you are reporting a bug for a completely different shader. this is the "bliss shader" github, you want the "photon shader" github.

**Comment by wtf8hz4rj2-max** [comment]
X0nk asi es nesecito el de photon shaders pero, el shaders que tengo se llama Erbium copia de los photon shader, es prácticamente igual el detalle es que este si me va bien en mi pc y los photon no, solo me interesaría solucionar el error de la armadura que no se ve bien:(

**Comment by X0nk** [comment]
Perdóname por usar un traductor.

Yo no fabrico "photon" ni "erbium" Los problemas que tienen esas cosas no me importan.

**Comment by wtf8hz4rj2-max** [comment]
Entonces quien me puede ayudar en eso?

**Comment by X0nk** [comment]
Vaya a las rutas de soporte "photon" o "erbium".

https://modrinth.com/shader/photon-shader

**Comment by wtf8hz4rj2-max** [comment]
Gracias!
