### ISSUE TITLE
Graphics looks downgraded

### ISSUE THREAD

**Issue by EQQx110** [X0nk/Bliss-Shader#138]
![2024-05-26_09 07 19](https://github.com/X0nk/Bliss-Shader/assets/108895045/061a74fe-709b-4ca1-9c1f-9f3afb133a77)
![2024-05-26_09 07 25](https://github.com/X0nk/Bliss-Shader/assets/108895045/14c20b34-bf69-4ac5-adc3-46ce40fe5c4c)

Comparing the latest version to the previous I was using the graphics looks worse. Took both screenshots with default settings.

First the "downgrade" on clarity: seems tied to fog, I'm trying to fiddle with the fog settings but can't replicate the look of the older version. Yet the decision on the look of fog in this aspect is arbitrary of the creator (if this change was done on purpose), so it could also be not considered a downgrade. I don't know if the sharpness or TAA were changed and contribute to the blurriness.

Then the lighting: shadows, like under the leaves, don't look as good. Changing the SSS mode to "LabSSS only" makes it similar to the older version but it still looks worse.

Lastly, rain is barely visible.

**Comment by EQQx110** [comment]
Anyway setting SSS density to 2.0 seems to fix the shaded areas, and looks better than the older version.

**Comment by X0nk** [comment]
the visual change to the fog and rain is because of one thing; i changed bloom
the "bloomy fog" effect uses bloom to make it look soft, and hazy. and rain drops exist exclusively as bloom.
i plan to do something about this, as i do not like how the new bloom looks in this scenario.
