### ISSUE TITLE
Hand held lighting doesn't work

### ISSUE THREAD

**Issue by EQQx110** [X0nk/Bliss-Shader#139]

**Comment by X0nk** [comment]
it currently only works when floodfil lighting is enabled. this will be fixed eventually.
shader settings -> ambient light-> floodfill

**Comment by chair-man-f** [comment]
> it currently only works when floodfil lighting is enabled. this will be fixed eventually. shader settings -> ambient light-> floodfill

is floodlight supposed to work on macos? doesn't work for me

**Comment by X0nk** [comment]
oh... yeah that wont work on macOS

**Comment by chair-man-f** [comment]
> oh... yeah that wont work on macOS you will have to wait till i fix it.

ssgi doesn't work either

but it works on other shaders like super duper vanilla
