### ISSUE TITLE
Error when entering Nether with SSR enabled

### ISSUE THREAD

**Issue by ShrikerChestTree** [X0nk/Bliss-Shader#14]
Nether with SSR on looks like this:
![2023-07-20_23 04 50](https://github.com/X0nk/Bliss-Shader/assets/107254774/80b90e09-803e-477e-8f70-a42cc31530fb)
![2023-07-20_23 04 53](https://github.com/X0nk/Bliss-Shader/assets/107254774/0ec47d43-829d-4355-82e1-13dc44c6ac42)
Here is the error itself that I copied in the post:

composite2.fsh: composite2.fsh: ERROR: 0:344: 'rayTraceSpeculars' : no matching overloaded function found (using implicit conversion) 
ERROR: 0:344: 'rayTraceSpeculars' : function is not known 
ERROR: 0:343: '=' : cannot convert from 'const highp float' to '3-component vector of highp float'.

I hope you fix it.

**Comment by X0nk** [comment]
what version of bliss are you using? try the latest commit.

**Comment by ShrikerChestTree** [comment]
> what version of bliss are you using? try the latest commit.

Bliss 20.07.2023 github version
