### ISSUE TITLE
Shadows in angles that shouldn't be

### ISSUE THREAD

**Issue by EQQx110** [X0nk/Bliss-Shader#140]
![2024-05-26_14 14 40](https://github.com/X0nk/Bliss-Shader/assets/108895045/d7aff50a-047a-4ab2-bded-30765d7ab9c6)

Shadows appear inside angles, this effect is even more visible when activating POM.

**Comment by chair-man-f** [comment]
what resource pack is that? also the dark spots on the edges is ambient occlusion

**Comment by X0nk** [comment]
its not ambient occlusion, but the actual shadowmap.
this is a side-effect of trying to workaround another issue with the shadows, and is a minor artifact usually. shadows can get kinda funky on spots with deeper POM, and make it alot more visible.

**Comment by EQQx110** [comment]
> what resource pack is that? also the dark spots on the edges is ambient occlusion

Pixilli; in the screenshot I was using Pixilli V29, (I edited it to remove the spruce leaves textures because they looked ugly).
Now I updated to the last version you can find here (spruce leaves still look ass):
https://modrinth.com/resourcepack/pixlli/versions#all-versions
