### ISSUE TITLE
idk the game said invalid program "composite2"

### ISSUE THREAD

**Issue by vangcuoi** [X0nk/Bliss-Shader#141]
![Screenshot 2024-05-27 164845](https://github.com/X0nk/Bliss-Shader/assets/79014002/24cd1070-2d6b-4aea-a93a-6ef37e331e3d)
![Screenshot 2024-05-27 164355](https://github.com/X0nk/Bliss-Shader/assets/79014002/1ea3e124-d2d6-4174-aa88-3dc0120c1c0f)

**Comment by vangcuoi** [comment]
> could you send a screenshot with the f3 overlay fully visible? and if you could, sent the "latest.log" file after the error happens in-game (It updates live as the game plays). this log would be the most useful information. it should be in .minecraft/logs

![Screenshot 2024-05-28 174933](https://github.com/X0nk/Bliss-Shader/assets/79014002/dc857bc9-8c75-40ee-be7f-ec588085add7)
[latest.log](https://github.com/X0nk/Bliss-Shader/files/15468033/latest.log)

**Comment by X0nk** [comment]
try using the latest in-development version

**Comment by vangcuoi** [comment]
> try using the latest in-development version

ye it work fine now
