### ISSUE TITLE
white water, looks like mold

### ISSUE THREAD

**Issue by Mariuszko10** [X0nk/Bliss-Shader#142]
i will attach a picture
![image](https://github.com/X0nk/Bliss-Shader/assets/75446696/8b76d92b-8915-428e-84d9-1898a14805e3)
![image](https://github.com/X0nk/Bliss-Shader/assets/75446696/8463c8df-979c-4139-9e98-d62432326b5c)

**Comment by Mariuszko10** [comment]
no its not snow

**Comment by Mariuszko10** [comment]
and i just found out its a lightning problem, with light

**Comment by X0nk** [comment]
turn it off in shader settings -> climate -> seasons
