### ISSUE TITLE
Shader failed to load with distant horizons.

### ISSUE THREAD

**Issue by Rouf0x** [X0nk/Bliss-Shader#143]
When loading the shader with distant horizons on Iris I get the following error:
"The shaderpack failed to load! Please report the error to the shader developer. Copy info"
Attachement: 
![image](https://github.com/X0nk/Bliss-Shader/assets/61273311/f3997325-cf02-4b79-a081-f65313c69a22)

The error is:  text_bg.vsh: text_bg.vsh: 0(99) : error C1503: undefined variable "entityId"

My current mod list is:
- Distant horizons ver. 2.0.1
- indium 1.0.25
- iris 1.6.8
- modmenu 7.2.2
- sodium 0.5.2
- fabric api 0.92.1

My minecraft version is 1.20.1 and my mod loader is Fabric 0.15.11

Screenshot after the error:
![image](https://github.com/X0nk/Bliss-Shader/assets/61273311/aeb09f05-5f14-4cac-b9c0-deeeee8f8f57)

**Comment by UnknownSuperficialNight** [comment]
getting the same things using the dev version 1.19.4

**Comment by Rouf0x** [comment]
# How I Fixed the Issue

@UnknownSuperficialNight You can resolve the problem by installing Iris using the "Iris Installer" rather than the mod itself.

If you want to add other mods along with Distant Horizons and a shader, follow these steps:

- In the installer, select "Iris Only."
- Go to your .minecraft folder.
- Open the "iris-beta-reserved" folder.
- Inside, find and open the folder corresponding to your Minecraft version.
- Drag and drop all the mods you want to add alongside Iris and Distant Horizon into this folder.
