### ISSUE TITLE
Strange outline effect in corners of blocks

### ISSUE THREAD

**Issue by xdomix723** [X0nk/Bliss-Shader#144]
![image](https://github.com/X0nk/Bliss-Shader/assets/171092697/7a6b289b-bdeb-4f48-8e3e-a622d160851b)
![image](https://github.com/X0nk/Bliss-Shader/assets/171092697/6b53a82e-1813-4775-a97f-a66078c48000)

**Comment by X0nk** [comment]
this is the shadowmap, and is an unavoidable artifact. it comes from working around a different shadowmap issue where it has a gap between what casts the shadow, and the shadow itself.

in more technical terms, its to stop "peter panning" when i "bias" the shadowmap. i bias the shadowmap using the normals of the geometry. [this describes some shadowmap issues every shadowmap has to deal with, including peterpanning](https://learnopengl.com/Advanced-Lighting/Shadows/Shadow-Mapping)
