### ISSUE TITLE
Issue or not? Missing Rain Puddle Reflections

### ISSUE THREAD

**Issue by WL121212** [X0nk/Bliss-Shader#146]
I have been using your shader pack and noticed that there are no visible reflective rain puddles or reflective surfaces when it rains in the game. I have reviewed the shader code and found references to puddles and reflections, but these effects do not seem to be active or visible during rain, when I am playing.

Could you please confirm if this is a bug or if there is a specific setting or additional step required to enable reflective rain puddles and surfaces? I have ensured that the relevant settings such as Puddles are enabled in the shader configuration, but the reflections still do not appear.

Your guidance on how to activate or fix this feature would be greatly appreciated. Reflective rain effects are a fantastic addition to the experience, and I would love to see them working correctly.

Thank you for your help and for providing such an amazing shader pack!

[ Minecraft 1.20.4 + Iris 1.7.0, no additional Recource Pack in use ]

**Comment by X0nk** [comment]
you need labPBR specular reflections enabled for them to work.
