### ISSUE TITLE
VPS causing artifacts

### ISSUE THREAD

**Issue by Prime54601** [X0nk/Bliss-Shader#147]
![2024-06-01_09 38 40](https://github.com/X0nk/Bliss-Shader/assets/143816248/513be2f8-2d85-4047-bceb-e11208ec3f57)
When VPS is enabled the shadows got kinda split into two layers, after disabling VPS this problem goes away
F3 screenshot and game log:
![2024-06-01_10 00 41](https://github.com/X0nk/Bliss-Shader/assets/143816248/fe2d0e5f-6d68-4d2f-860d-111c704b5249)
[latest.log](https://github.com/user-attachments/files/15520089/latest.log)
Shader config:
[Bliss-Shader-main.txt](https://github.com/user-attachments/files/15520095/Bliss-Shader-main.txt)

**Comment by Prime54601** [comment]
Also this only happens on blocks with subsurface scattering like snow

**Comment by X0nk** [comment]
yeah... thats a thing. just a small problem with the VPS sampling shape not being perfectly smooth
