### ISSUE TITLE
water dispeared through the glass

### ISSUE THREAD

**Issue by g-mero** [X0nk/Bliss-Shader#148]
latest commit version([14b20cd](https://github.com/X0nk/Bliss-Shader/commit/14b20cdcfc1f54d3aa3f7562e89e0fb0a333b82c)).

https://github.com/X0nk/Bliss-Shader/assets/62990607/a89f3c51-6e52-4980-93a0-d7033c0363cf

**Comment by g-mero** [comment]
Other support-DH shader, photon, Shrimple and BSL don't have this issue.

Here is my F3 info.
![2024-06-01_14 09 19](https://github.com/X0nk/Bliss-Shader/assets/62990607/b0488ff1-b6ec-4b27-ad9d-812720070a38)

**Comment by X0nk** [comment]
this is a sodium thing. it does not have translucent sorting in released versions (yet).
