### ISSUE TITLE
Leaves and grass added by mods have no SSS effect

### ISSUE THREAD

**Issue by Xposeded** [X0nk/Bliss-Shader#15]
Leaves and grass added by mods have no SSS effect, while those in the vanilla Minecraft have.
I am not sure if it's because I didn't get the right setting of shader or it's a compatitibility issue in Oculus.
Using Minecraft-1.18.2, forge-40.2.1, Oculus-1.6.4, Rubidium-0.5.6 and other mods that should have nothing to do with shaders.
Some screenshots in comparison with other shaders that work as expected:
![image](https://github.com/X0nk/Bliss-Shader/assets/26787211/24864d7f-e188-4cf9-9481-27b101830352)
![image](https://github.com/X0nk/Bliss-Shader/assets/26787211/6a3f4d40-cc7d-4de3-b612-8449f1ffd011)
![image](https://github.com/X0nk/Bliss-Shader/assets/26787211/6123ee2a-b3e1-4c3c-abac-75420273d38e)

**Comment by X0nk** [comment]
This is natural, and not a bug. I had to make a list of blocks to make SSS work on with unmodded blocks. you will just have to add the modded blocks ID to the`block.properties` text file, and add them to whichever of the groups of ID's that have similar blocks. Those other shaders simply added the block ID's to their lists, because that is a common mod or something.

it is _impossible_ to automatically detect what blocks should get SSS or not without any information to help out, like a resourcepack.

**Comment by Xposeded** [comment]
> This is natural, and not a bug. I had to make a list of blocks to make SSS work on with unmodded blocks. you will just have to add the modded blocks ID to the`block.properties` text file, and add them to whichever of the groups of ID's that have similar blocks. Those other shaders simply added the block ID's to their lists, because that is a common mod or something. you can find their block.properties and copy paste the listed ID's into bliss's lists, to make it easier.
> 
> it is _impossible_ to automatically detect what blocks should get SSS or not without any information to help out, like a resourcepack.

Thanks for answering, this really helped a lot for me! After adding blocks IDs, things do look way much better in areas with dense flora. 
![image](https://github.com/X0nk/Bliss-Shader/assets/26787211/95e64292-68d7-41b7-a041-cad8cd84533e)

By the way, the grass looks a little bit of too dark which makes it not really match the environment visually, is there any way to make them brighter? Here are the screenshots for comparison:
![image](https://github.com/X0nk/Bliss-Shader/assets/26787211/fbfbceb0-0b97-4e8a-bc1d-7f35464d2556)
![image](https://github.com/X0nk/Bliss-Shader/assets/26787211/cb9615ca-6669-4886-886b-00795a22d28c)
![image](https://github.com/X0nk/Bliss-Shader/assets/26787211/c255d1a3-fd2b-4ea7-b79d-723c4125b5ce)
![image](https://github.com/X0nk/Bliss-Shader/assets/26787211/1d3e12b3-9e8f-4050-9e0c-e54eaa904ae5)
![image](https://github.com/X0nk/Bliss-Shader/assets/26787211/4753f65f-66e5-4d18-8b2d-67fc6e592a81)

**Comment by X0nk** [comment]
that grass simply gets the same shading as everything else. see how the sides of blocks are darker than the up facing parts? the grass is 100% sides. so it gets the darker shade as well. SSS from the sky should help brighten them up.

for them to be brighter i would have make a special case and shade them slightly differently than everything else.

**Comment by Xposeded** [comment]
> that grass simply gets the same shading as everything else. see how the sides of blocks are darker than the up facing parts? the grass is 100% sides. so it gets the darker shade as well. SSS from the sky should help brighten them up.
> 
> for them to be brighter i would have make a special case and shade them slightly differently than everything else.

Yes, I do notice that the vanilla Minecraft rendering would darken the side faces of a block to make it easier to distinguish different faces. I can't tell whether or not the grass in vanilla Minecraft rendering is influenced by this method, but its color or brightness do match the land it attached to.
These screenshots would be helpful explaining what I talked about (Shadow map is disabled):
![image](https://github.com/X0nk/Bliss-Shader/assets/26787211/3f1b19a0-1ae9-4e0c-ad7c-9230c394cffb)
![image](https://github.com/X0nk/Bliss-Shader/assets/26787211/6dd8a9ed-fece-44b8-a87a-31e474ccc3a5)
![image](https://github.com/X0nk/Bliss-Shader/assets/26787211/54c73a76-c589-4369-a192-2a5cf74bd777)
![image](https://github.com/X0nk/Bliss-Shader/assets/26787211/0ae5b426-6a32-486e-9efe-d89c6876ea43)
Hope these could help figuring out what goes wrong  : )

**Comment by X0nk** [comment]
in the latest commits i have brightened the grass to be the equivalent of a surface almost facing straight up, so it gets a brighter shade compared to before.
