### ISSUE TITLE
Players incorrectly lit with RTAO and SSGI when not affected by ambient light

### ISSUE THREAD

**Issue by Deevian** [X0nk/Bliss-Shader#151]
Players are incorrectly lit (i.e. not lit at all) when using RTAO or SSGI and when not affected by ambient light.

In other words: when in caverns (e.g.), players appear completely black:

![broken](https://github.com/X0nk/Bliss-Shader/assets/1906428/8228b1c5-60c4-4404-b3ea-fd4fb8e88c5b)

On the surface, they're correctly lit, though not affected by torches or other sources of light:

![broken1](https://github.com/X0nk/Bliss-Shader/assets/1906428/2f096b57-850c-4f4d-8d52-fc532e3771ea)

Other entities, such as bats or zombies, appear to be correctly lit in caverns; this seems to only affect the player character.

Tracked down the cause to this commit (though by the size of it, it might not help narrow down the cause 🙈):

https://github.com/X0nk/Bliss-Shader/commit/25a2284a60e9d466af46d64ede8ac78f200698dc

For context, here is how it looked before that version:

![working](https://github.com/X0nk/Bliss-Shader/assets/1906428/b80ec872-47ca-443c-b2b2-cb13245e3c9a)
![working1](https://github.com/X0nk/Bliss-Shader/assets/1906428/c6dfcd4f-61bf-49bc-84ca-a7fb68b9a216)

**Comment by Deevian** [comment]
Actually, never mind me, after more investigation this is actually related to FloodFill. Turning it off makes it so the player is correctly lit.

Closing this as the description does not match the actual issue.

**Comment by Deevian** [comment]
Might be related to this: https://github.com/X0nk/Bliss-Shader/blob/14b20cdcfc1f54d3aa3f7562e89e0fb0a333b82c/shaders/lib/indirect_lighting_effects.glsl#L398

Removing that line mostly fixes the issue:

![imagem](https://github.com/X0nk/Bliss-Shader/assets/1906428/2d101ffe-c326-4793-bec6-01ea84639aa4)

Hand torches are still not correctly emitting light, but are probably unrelated to the above.

**Comment by X0nk** [comment]
this should be fixed now
