### ISSUE TITLE
Sky breaks with DH LOD rendering

### ISSUE THREAD

**Issue by Lukxie** [X0nk/Bliss-Shader#154]
Minecraft version: 1.20.1
DH version: 2.0.4-a-dev 
Oculus version: 1.7.0
Bliss-Shader version: latest in-development
The sky fills up with whatever is on the floor, whenever I turn off DH LOD rendering it fixes.

![image](https://github.com/X0nk/Bliss-Shader/assets/115797570/5ae1955b-3685-4f2d-898d-ae2fdd506337)
![image](https://github.com/X0nk/Bliss-Shader/assets/115797570/7ece80d5-f872-4aaf-ae36-97534230a2e7)

**Comment by X0nk** [comment]
this is a super common issue related to iris
there are a few ways to get around it.
restart the game this is just DH crashing. if restarting does not fix it go to Distant horizons settings -> advanced options -> graphics -> rendering -> change transparency to complete

**Comment by Lukxie** [comment]
It was always set to complete

![image](https://github.com/X0nk/Bliss-Shader/assets/115797570/148ad2b6-34f7-48ca-a55b-c6d2bd7b2064)

**Comment by X0nk** [comment]
well, then... i am unsure how to fix this. you'll have to talk to the iris people, or distant horizons people directly

**Comment by Lukxie** [comment]
Turns out it was an issue with Alex's caves which had been reported before https://github.com/AlexModGuy/AlexsCaves/issues/519
