### ISSUE TITLE
Any moving parts from Create causing huge frame rate issues with bliss.

### ISSUE THREAD

**Issue by woflmao** [X0nk/Bliss-Shader#158]
As the title states, using Create along with bliss causes huge frame late issue. I know this because when I disable the shader pack frames jump back to expected level, and even walking around the corner is enough to not get the frame lag, it's only when you are looking at it or near it.

 Is there already a work around for this that I've missed? I have tried googling to no avail.

**Comment by Merlin1809** [comment]
Did you try adding this mod? Almost no framedrop for me.
https://www.curseforge.com/minecraft/mc-mods/iris-flywheel-compat

**Comment by X0nk** [comment]
flywheel get's disabled when shaders are enabled. as Null explained in your last duplicate issue you made....

**Comment by null511** [comment]
> Did you try adding this mod? Almost no framedrop for me. https://www.curseforge.com/minecraft/mc-mods/iris-flywheel-compat

also please do not recommend this mod, it causes many shader issues because it's not really flywheel compatibility. It just forces it back on and lets things break.
