### ISSUE TITLE
[Bug] Visual Issue with Maps

### ISSUE THREAD

**Issue by 123ghaksd** [X0nk/Bliss-Shader#159]
With Bliss-Shaders on, it seems to effect maps in a strange way (Only in Overworld). This is with no mods other than Iris, Sodium, and Fabric API. Tested with latest release and latest build. The latest build does not have this issue, however I prefer the style of the latest release. Is there a way to manually fix this (ex. switching out a file)?

![2024-06-07_13 38 17](https://github.com/X0nk/Bliss-Shader/assets/88822402/c4e5c3d6-0eb0-4f8f-be11-df76784b12f9)

**Comment by 123ghaksd** [comment]
If anyone knows a solution plz lmk. The development version is just not same.

**Comment by 123ghaksd** [comment]
Correct

**Comment by X0nk** [comment]
hm well... uh... i dont really want to do support for a bug ive already fixed on newer versions.
soon, the blue, clean feeling of bliss v2.0.4 will make a comeback in some way.
