### ISSUE TITLE
error invalid program

### ISSUE THREAD

**Issue by 2009pim2009** [X0nk/Bliss-Shader#160]
when i try to use the shaders on 1.16.4 i get eroor invalid program and a hole list of programs
that i could be the mods that i use tested that dint work
i also saw that modrinth says the shader is 1.17+
but curseforge says 1.16.5 is supported
depending on the shader version the following things happen
shaders dont apply/nothing changes
all colors are mixed
everything becomes blurry
i get the same porblems on optifine and on oculus
conclution its bc i use forge or 1.16.5 or smth else 
is there a solution?
list of error (all of these have: [shaders] error: invalid program before them)
shadow
gbuffers_basic
gbuffers_textured
gbuffers_texted_lit
gbuffers_terrain
gbuffers_demagedblock
gbuffers_block
gbuffers_entities
gbuffers_hand
weather
deferred
deferred1
deferred2
gbuffers_water
gbuffers_hand_water
composite
composite1
composite2
composite3
composite5
composite11
final

**Comment by X0nk** [comment]
this shader uses features that do not exist for any shader mod loader for 1.16.5

**Comment by 2009pim2009** [comment]
please change the curseforge page

**Comment by X0nk** [comment]
i swear i removed 1.16.5 from it D:
i will get to doing that
