### ISSUE TITLE
Huge bug on  RTAO with High Quality Ambient light on

### ISSUE THREAD

**Issue by Sleepwalker217** [X0nk/Bliss-Shader#161]
With these particualar setting, during night all the areas that should've been even darker (shadow from trees, under some blocks etc) are fully bright. I think can be just wrong 0 light param. Minimum Brightness Level doesn't help with it 
![2024-06-07_19 51 45](https://github.com/X0nk/Bliss-Shader/assets/50114710/62a915e1-55b6-4ea4-bf88-1a3bc098c0bb)

**Comment by X0nk** [comment]
yep this will be fixed in the next commit

**Comment by X0nk** [comment]
this has been fixed
