### ISSUE TITLE
[REQUEST] More weather randomness

### ISSUE THREAD

**Issue by Sleepwalker217** [X0nk/Bliss-Shader#163]
NOT AN ISSUE\BUG, CLOSE IT IF YOU WILL NOT BE MAKING IT 

1) If you already made day-dependant (moon phase i suppose) settings and SOMEHOW (with some black magic) made random pick in Daily Weather using only GLSL, why not to make like True Daily Weather, that will change all the daily weather params randomly every day. I am managed to make a script that doing it for me but i still need to restart the shader to apply

2) Can you make randomly changing seed of cloud pattern? Patterns are now pretty much obvious

**Comment by X0nk** [comment]
i am actually making daily weather system with settings profiles (individual coverage and density settings, for 3 different cloud layers. and some fog too)

there are 10 profiles for 10 different possible days. you will be able to have it choose one of those profiles randomly at the start of each new day, or cycle through them from 0 to 9 as the days pass by.

cloud shapes/patterns are not random, so there is no seed. its all made using noise textures.

**Comment by Sleepwalker217** [comment]
yea, I saw about profiles, but I was thinking about absolute random of it every day, not just circulating of presets

and that's sad about noise texture :(

**Comment by X0nk** [comment]
daily weather default profiles have been added. you should check them out
