### ISSUE TITLE
When mobs burn in the sun, the flames on their bodies render incorrectly

### ISSUE THREAD

**Issue by fuanxka** [X0nk/Bliss-Shader#166]
Minecraft: 1.20.1
Fabric: 0.15.11
Iris: 1.7.0
Bliss: main branch

It's too black.
![2024-06-10_03 10 43](https://github.com/X0nk/Bliss-Shader/assets/68276806/42532269-7976-4b9c-bfb1-81c7d81bad06)

It seems to have something to do with me opening FloodFill.

**Comment by X0nk** [comment]
this only happens with floodfill enabled. it will be fixed.

**Comment by X0nk** [comment]
this has been fixed
