### ISSUE TITLE
Screen smear when moving camera

### ISSUE THREAD

**Issue by bekkos** [X0nk/Bliss-Shader#169]
Getting this sort of "screen smear" when using Iris + Sodium + Latest version of DH + In dev version of Bliss shader. All default settings on all mods.

![2024-06-10_16 01 49](https://github.com/X0nk/Bliss-Shader/assets/26651713/808372e5-1d17-454b-b796-ffafd2636211)

**Comment by xanderiom** [comment]
in DH config, at least for me, anything above medium quality preset fixes this for me. Minimum/Low causes the smearing

**Comment by OrangeSniper** [comment]
> in DH config, at least for me, anything above medium quality preset fixes this for me. Minimum/Low causes the smearing

this does not work for me

**Comment by OrangeSniper** [comment]
this seems to be an issue with DH, as it happens with Proton shaders too

**Comment by null511** [comment]
correct, DH/Iris issue completely unrelated to shaders.

**Comment by OrangeSniper** [comment]
this is due to a compatibility issue with Alex's Caves see [this](https://gitlab.com/jeseibel/distant-horizons/-/wikis/2-frequently-asked-questions/4-mod-support/Mod-Support) for solution
