### ISSUE TITLE
Light bug with glass?

### ISSUE THREAD

**Issue by TheRealPicasso** [X0nk/Bliss-Shader#17]
Hey, are there specific options to fix this? Also some templates for the shader to get best possible results would be cool! I love the shader skies!

Heres the link for the image of my bug: https://ibb.co/YPVL3t2

**Comment by X0nk** [comment]
Are you referring to the beacon beam being dark? because i see no other issues besides that in the image.

**Comment by TheRealPicasso** [comment]
> Are you referring to the beacon beam being dark? because i see no other issues besides that in the image.

No im talking about the white reflections, which look weird, because those are wood blocks, which shouldnt be that bright, it seems more like an reflection issue (due sunlight and glass + another light source)

**Comment by X0nk** [comment]
those white splotches? thats snow from the seasons.
you can turn it off in shader settings -> climate -> seasons

**Comment by TheRealPicasso** [comment]
> those white splotches? thats snow from the seasons. you can turn it off in shader settings -> climate -> seasons

Oh damn, it was indeed the snow! Thanks for the help, i wouldnt have figured it out :) great shader!
