### ISSUE TITLE
Tall Grass Texture Glitch

### ISSUE THREAD

**Issue by SmilinGisli** [X0nk/Bliss-Shader#171]
Does anyone know what setting I could change to fix this tall grass texture bug when enabling this shader? For now this is only affecting my tall grass.
![Screenshot 2024-06-10 153408](https://github.com/X0nk/Bliss-Shader/assets/122424040/704935a6-d589-431b-a6f3-3f6032b47f7b)

**Comment by X0nk** [comment]
that is not a shader issue, but a resourcepack issue.

**Comment by SmilinGisli** [comment]
> that is not a shader issue, but a resourcepack issue.

Yes I was just coming back here to say that I now can use any shader by just turning off the wave plant effect.
