### ISSUE TITLE
No fog when looking through glass

### ISSUE THREAD

**Issue by bennus-bob** [X0nk/Bliss-Shader#179]
![2024-06-11_20 38 42](https://github.com/X0nk/Bliss-Shader/assets/172432327/8cb88e53-ad15-45a4-81c3-d0507c23517a)
There is no fog when looking through glass. How can i fix this? it looks very weird.

**Comment by X0nk** [comment]
what version of bliss are you using? because i have fixed this on the latest in-development version. if it still happens on that, it is sodiums lack of translucent sorting causing it.

**Comment by bennus-bob** [comment]
Ah i was using the latest version on curseforge. thank you!

**Comment by notkanyewest** [comment]
I'm still getting this error on the latest in-development version
![image](https://github.com/user-attachments/assets/37283ae7-c952-44a5-a26f-56a7e93b5df3)

**Comment by X0nk** [comment]
whar

**Comment by notkanyewest** [comment]
how do you suggest i fix that?

**Comment by X0nk** [comment]
theres a setting to adjust bloomy fog in `shader settings -> fog settings -> bloomy fog`

**Comment by notkanyewest** [comment]
thank you. i only have render clouds as fog on because i have places up in the mountains where there are clouds so it's nice to have that.
