### ISSUE TITLE
Transparent Skin

### ISSUE THREAD

**Issue by TheIdiot0** [X0nk/Bliss-Shader#180]
AHH! Im a Ghost!
My skin is transparent... thats really it.
Vanilla:
![image](https://github.com/X0nk/Bliss-Shader/assets/114532380/fc748e76-d38c-44a6-8585-bc2202870355)
Bliss:
![image](https://github.com/X0nk/Bliss-Shader/assets/114532380/edb0b920-7cbc-48ad-a706-4ac8d737b490)

**Comment by X0nk** [comment]
this is caused by my blending type for translucent entities. it only renders the front most part. i can change this. i only did that because it looked good on slimes.... i didnt think about player skins.

**Comment by X0nk** [comment]
this should be fixed now, go re-download.

**Comment by TheIdiot0** [comment]
thx
