### ISSUE TITLE
Rendering Bug With Distant Horizons

### ISSUE THREAD

**Issue by Blocky-Sphere** [X0nk/Bliss-Shader#183]
I dont know how to describe it. It's just rendering a weird repeating stuffs on the sky. There is no bug while not installed with Distant Horizons.
![Screenshot with f3](https://github.com/X0nk/Bliss-Shader/assets/172484810/f2d7fc7f-9dea-45c7-baa2-69d72b1bbda0)
![Screenshot](https://github.com/X0nk/Bliss-Shader/assets/172484810/903b4ca3-f09b-4301-8396-16f85e84545d)

**Comment by X0nk** [comment]
a. restart the game this is just DH crashing. 
b. if restarting does not fix it go to Distant horizons settings -> advanced options -> graphics -> rendering -> change transparency to complete 
c. remove the "alex's caves" mod

**Comment by Blocky-Sphere** [comment]
it works. thank you

**Comment by Blocky-Sphere** [comment]
Thanks
