### ISSUE TITLE
DH shadows are flickering when move

### ISSUE THREAD

**Issue by SukiruQuinn** [X0nk/Bliss-Shader#185]
### I disabled every graphics option in the shader for visual purposes? but none of them fix the problem at all
![image](https://github.com/X0nk/Bliss-Shader/assets/172456716/24ecd12c-db08-4121-bb89-baf0e6f72f2f)
![image](https://github.com/X0nk/Bliss-Shader/assets/172456716/703f930b-448d-4b4a-b738-7af6045f5f2c)
![image](https://github.com/X0nk/Bliss-Shader/assets/172456716/6556ffa3-1349-4fb1-af23-6507fa50a2de)

### also if the TAA is disabled the shader isn't working till it's ON again (same as Aerochrome mode)
![image](https://github.com/X0nk/Bliss-Shader/assets/172456716/8e13cce3-6b91-4bfb-b3bf-2fc6540d9b5a)

![image](https://github.com/X0nk/Bliss-Shader/assets/172456716/b71b4607-aec2-43b5-bf89-71999c8d2e3f)

**Comment by X0nk** [comment]
This is a bug that happens specifically on AMD drivers. i knew about it, but i haven't got around to investigating it yet (sorry about that)
the other issue with TAA and aerochrome mode will be fixed shortly, the flickering problem will take a little longer to figure out!

**Comment by SukiruQuinn** [comment]
No problem, thx for ur support and work for this awesome shader, because of bliss and DH truly we are havin a new era of minecraft, u are a legend!

**Comment by X0nk** [comment]
this has been fixed

**Comment by Z1Tou** [comment]
This is happening to me on a NVIDIA Gpu, I'm not sure if it's related but it comes from the sun and clouds? The shadows are also always connected to the player if that helps but there's a lot of flickering still. I'm using the latest version and I think this happens with any version even with vanilla settings
