### ISSUE TITLE
DoF makes glass illegibly blurry.

### ISSUE THREAD

**Issue by Nekrozmik** [X0nk/Bliss-Shader#188]
![2024-06-12_19 37 07](https://github.com/X0nk/Bliss-Shader/assets/67240103/144b4cba-745d-4822-914a-240966bbbfc0)

![2024-06-12_19 37 13](https://github.com/X0nk/Bliss-Shader/assets/67240103/48cda950-c538-497f-a85f-a93f464622c9)

I tried testing it with and without refraction, it didn't seem to change anything.
This happens on all types of glass and translucent blocks that I've tested so far.

All that is needed to reproduce this is to turn on depth of field (autofocus seems to make it more obvious as well) and look through glass. 
If I had to assume, it seems the focus plane goes through the glass (which is good) but it also blurs the glass itself due to this (which is bad). Or maybe they're just the wrong prescription.

**Comment by X0nk** [comment]
This is caused by the DOF focus depth using the depth buffer that includes translucent things for the "circle of confusion" calculation.
its an easy fix. though, translucent things will not get blurred exactly as one would expect.... not like it did before.

**Comment by X0nk** [comment]
this is fixed. go redownload
