### ISSUE TITLE
Feature request: bloom-based colored lighting.

### ISSUE THREAD

**Issue by VjIwd05VNUJQVDA9** [X0nk/Bliss-Shader#19]
A feature was recently added to the [Solas](https://modrinth.com/shader/solas-shader) shader ([V1.5b](https://modrinth.com/shader/solas-shader/version/1.5b)) that, according to the shader's description on Modrinth, makes use of bloom to create an illusory colored lighting effect (demonstrated in the attached screenshot). It looks great and has virtually no performance impact, and IMO would make for a great addition to Bliss as well.

![screenshot](https://github.com/X0nk/Bliss-Shader/assets/143306635/bb28b43b-1089-4ed4-86ee-41453193e2db)

**Comment by X0nk** [comment]
i'm gonna just be completely honest, i don't really want to add it.
i have nothing against the work done b the developer of solas or the shader itself, i'm simply just not so interested.
