### ISSUE TITLE
Clouds Intersect Terrain with Translucent Entities causes clouds to render above players and nametags.

### ISSUE THREAD

**Issue by Nekrozmik** [X0nk/Bliss-Shader#190]
![2024-06-13_04 16 26](https://github.com/X0nk/Bliss-Shader/assets/67240103/5331eec1-9470-4a4a-8f46-6c0dd1f875c4)
![2024-06-13_04 16 34](https://github.com/X0nk/Bliss-Shader/assets/67240103/b0a922a4-e35f-42b1-a66c-93e1c7c8701f)
![2024-06-13_04 30 57](https://github.com/X0nk/Bliss-Shader/assets/67240103/a53fecce-120b-41f4-9a66-d5bf40ed5eef)

Explained in title. Having both CLOUDS_INTERSECT_TERRAIN and TRANSLUCENT_ENTITIES on at the same time causes clouds to render above specifically players, oddly enough. Tested with other entities, no other ones had this same issue except nametags. I'm yet to test text displays and such, though.

(By the way, just wanted to add I really appreciate the drive you have working on this. Every time I check back here it seems there's more stuff and more fixes.)

**Comment by X0nk** [comment]
this can be explained quickly. when `CLOUDS_INTERSECT_TERRAIN` is enabled, it is composited onto the scene *after* translucents are composited onto the scene. so it shouldnt just do this on some entities, but on stuff like glass too. there isnt really a solution to this on the users end of things. `CLOUDS_INTERSECT_TERRAIN` is just a work in progress

**Comment by X0nk** [comment]
this was fixed
