### ISSUE TITLE
Autofocus misaligned when using Temporal Upscaling

### ISSUE THREAD

**Issue by Nekrozmik** [X0nk/Bliss-Shader#192]
![2024-06-13_04 55 29](https://github.com/X0nk/Bliss-Shader/assets/67240103/7dbb0983-1089-48e1-a9b0-a02a4c70564f)

Pretty self-explanatory. Turn on Temporal Upscaling, turn on DoF Autofocus and set DoF to Jitter and you'll see what I mean.

**Comment by X0nk** [comment]
ah. just a small oopsi doopsi

**Comment by Nekrozmik** [comment]
just updating that this is still an issue; it's mostly what stops me from using temporal upscaling since i like using DoF but using both causes me to feel like i'm playing minecraft with the wrong prescription. it's a shame too because it really bumps up my fps

**Comment by X0nk** [comment]
oh yeah i gotta get to this

**Comment by X0nk** [comment]
alright, all fixed up
