### ISSUE TITLE
GTAO makes light sources no longer emit light.

### ISSUE THREAD

**Issue by toasterdoggg** [X0nk/Bliss-Shader#193]
When using GTAO as the ambient light solution, blocks that should emit light like torches and glowstone simply don't do so. They still affect nearby speculars but no light is cast on their surrounding areas.

![2024-06-13_14 50 02](https://github.com/X0nk/Bliss-Shader/assets/77793935/ab33480b-6de2-47d8-ae28-2ca1fe1ed72d)
![2024-06-13_14 50 21](https://github.com/X0nk/Bliss-Shader/assets/77793935/2bb53f83-6d34-4108-b978-0b56f0270e30)

**Comment by X0nk** [comment]
ah.. yeah i always neglect GTAO. i will get to fixing this up

**Comment by X0nk** [comment]
this has been fixed
