### ISSUE TITLE
Glitching Skybox

### ISSUE THREAD

**Issue by Luca296** [X0nk/Bliss-Shader#195]
So my Bug is when i activate the Bliss shader with DH my Skybox just starts Glitching around and its like the sky represents waht i saw on the ground

![Screenshot (34)](https://github.com/X0nk/Bliss-Shader/assets/172833902/5c29816a-83c2-48c6-b92d-142e9e9ba2f5)

2. If you cannot do option 1. Please list the following information instead:
Im using an Nvidia 3060 12gb
Im on Windows 10 (the newest)
Im playing 1.20.4
Im using Feather Client but it also appears in normal Minecraft
Im using Iris
Im using the newest Dev Version for DH to work
Im using Distance Horizons

I dont think i need to make a vid but i will do a vid of the glitch

https://github.com/X0nk/Bliss-Shader/assets/172833902/dd446a0b-e443-46c5-a5ad-365a86ee80af

. Its just when i join a world it starts to glitch around

**Comment by SukiruQuinn** [comment]
DH is just crashing, restarting the game should solve it
otherwise try with Distant Horizons settings -> advanced options -> graphics -> rendering -> change transparency to complete

**Comment by X0nk** [comment]
Alex's caves can also cause this. disable Biome Ambient Light Coloring in the alex's caves config if you have that mod

btw this issue isnt caused by bliss, its an issue related to how iris and distant horizons work together. it just shows up in bliss for some reason
