### ISSUE TITLE
FloodFill Bed and Chest bug

### ISSUE THREAD

**Issue by mazutalors** [X0nk/Bliss-Shader#201]
Shadows around some (transparent?) objects like chests or beds are flickering when i move
It only happens when FloodFill is enabled
![2024-06-18_00 15 56](https://github.com/X0nk/Bliss-Shader/assets/61743099/9d5d9137-d9e8-4813-ae3d-3717a493bcfc)
![2024-06-18_00 16 04](https://github.com/X0nk/Bliss-Shader/assets/61743099/ba226c47-e144-4323-ad58-70a8c9f6da1b)
![2024-06-18_00 16 12](https://github.com/X0nk/Bliss-Shader/assets/61743099/1a5f1ad5-cd02-4fc1-9549-603be05a596d)
![2024-06-18_00 16 24](https://github.com/X0nk/Bliss-Shader/assets/61743099/b81cee37-9a85-41f4-bcc7-252e9cfaabb8)
![2024-06-18_00 16 29](https://github.com/X0nk/Bliss-Shader/assets/61743099/d49b4890-f687-4401-8d63-762419d99015)
![2024-06-18_00 16 35](https://github.com/X0nk/Bliss-Shader/assets/61743099/40f9433e-08f6-4ac7-a474-37d2dcc073c7)

**Comment by X0nk** [comment]
redownload the latest in-development version and see if it stops

**Comment by mazutalors** [comment]
seems to be fixed with the latest in-development version, thank you !
