### ISSUE TITLE
FloodFill rendering bug

### ISSUE THREAD

**Issue by Ultra119** [X0nk/Bliss-Shader#202]
Light and shadows are definitely not behaving normally with floodfill on.
Some information:
amd drivers
windows
minecraft 1.21

Video:
https://github.com/X0nk/Bliss-Shader/assets/64977575/3ad3f1bd-7be9-4565-8bb2-73995a80ee7f

Bliss config:
[Bliss-Shader-main.zip.txt](https://github.com/user-attachments/files/15878616/Bliss-Shader-main.zip.txt)

mods list:
[mods.txt](https://github.com/user-attachments/files/15878620/mods.txt)

**Comment by X0nk** [comment]
same as this issue [over here](https://github.com/X0nk/Bliss-Shader/issues/201)

**Comment by Ultra119** [comment]
> same as this issue [over here](https://github.com/X0nk/Bliss-Shader/issues/201)

mb mb, but I also have flickering lights.
