### ISSUE TITLE
Odd Flashing Light while in the End Dimension. 

### ISSUE THREAD

**Issue by WaryNiklas** [X0nk/Bliss-Shader#204]
Description:
While in the End Dimension with the shader I experience a flashing Orange light that pops up occasionally, akin to storm clouds. However, when I Drop the end storm intensity to 0 within the shader settings, the issue still persists.
![2024-06-18_11 42 49](https://github.com/X0nk/Bliss-Shader/assets/173196047/de77d433-58b7-4f43-8843-f2a3cde5d352)
![2024-06-18_11 42 43](https://github.com/X0nk/Bliss-Shader/assets/173196047/f9460f70-c8d8-4b8f-ab57-934915301e35)
![2024-06-18_11 42 47](https://github.com/X0nk/Bliss-Shader/assets/173196047/d36ef4b8-5a53-47ac-8731-9fcfc4d2b805)

~

![2024-06-18_11 45 00](https://github.com/X0nk/Bliss-Shader/assets/173196047/8b4fb202-2e9a-4598-9cf3-3f9a052eeae8)

The Bug appears on its own, whenever I enable the Bliss Shader. This occurs on both Single and Multiplayer.
Isolate the bug. some multiplayer servers cause issues on their own. in a newly made singleplayer world, with default/reset shader settings, show the steps to cause the bug

Mods List:
Cloth Config
Entity Culling
Fabric API
FerriteCore
Iris
Lithium
Mod Menu
Sodium
It appears within the End dimension in Vanilla, as well as well as mods such as Better End.
if a specific shader setting can make it start/stop bugging, please list what shader setting does that.
The settings that causes this is unknown to me.

**Comment by X0nk** [comment]
the flashing is lightning and is a feature.
lowering the end storm density doesn't do anything but... lower the density.
