### ISSUE TITLE
DistantHorizons LOD : Cherry Tree Leaves show up blue

### ISSUE THREAD

**Issue by OptiHuman** [X0nk/Bliss-Shader#209]
When using Bliss with Distant Horizon, Cherry Tree leaves render as a solid blue color in the LOD, they also flicker between normal color and blue. Issue goes away with another or no shader. 

**Mod List :** 

- Distant Horizons
- Fabric API
- Indium
- Iris
- Sodium

![2024-06-19_21 01 02](https://github.com/X0nk/Bliss-Shader/assets/102932146/983c4b35-6f1c-4ba3-a017-bda809a976c6)
![2024-06-19_21 00 56](https://github.com/X0nk/Bliss-Shader/assets/102932146/c825d86b-042c-48b8-986a-1a88c23677da)

**Comment by X0nk** [comment]
this is caused by the seasons coloring. still gotta figure out how to fix it.

**Comment by OptiHuman** [comment]
> this is caused by the seasons coloring. still gotta figure out how to fix it.

Hello! I did notice that after playing with the settings a bit more, thanks for confirming!
