### ISSUE TITLE
Partially discolored textures

### ISSUE THREAD

**Issue by trevelyan9** [X0nk/Bliss-Shader#21]
For some reason, with or without any resource packs, on both OptiFine and Iris, some textures such as grass, leaves and paths appear gray or discolored. It doesn't happen with other shaders, and it also doesn't happen with beta 1.15 version of your shader as well. I tried reinstalling everything to check if it's something on my side, but the problem's still there.

![2023-09-12_21 34 18](https://github.com/X0nk/Bliss-Shader/assets/129677292/9aa764c2-895f-480e-b3ef-4e3c0c5cc5c5)

**Comment by X0nk** [comment]
not a bug. that is the "seasons" feature. 
you can configure it in shader settings -> climate -> seasons
