### ISSUE TITLE
Jungle (possibly all per-biome) Fog/Environment applies to caves below Jungle

### ISSUE THREAD

**Issue by Excederus** [X0nk/Bliss-Shader#213]
### Describe the bug
Jungle Biome Fog/Environment applies to caves below Jungle too - did not test other biomes.
Opening the Sodium settings menu sometimes returns the fog to what it is supposed to be. Closing the settings the Jungle fog reappears after about a second.
Leaving and rejoining a world inside a cave below a jungle does not apply the jungle fog. However walking near a lightsource (in range for the light level to change) applies the jungle fog again and either returns to normal after a few seconds or stays applied when leaving the lit area.

### Describe how your minecraft is set up
Forgot to re-enable MC version in the F3 menu. It's 1.21
I am using the mod Void Fog alongside a few others, but this one should be the only one affecting caves and I disabled it and tested again in the video (this is a purely client-side pack).
Also happens with only latest Sodium and Iris.

Video of the following screenshots and a new green flicker on some blocks when the jungle fog doesn't apply: https://youtu.be/-diEbDyo11E
Screenshots of different scenarios with F3 menu
Shader on below jungle:
![2024-06-21_19 12 54](https://github.com/X0nk/Bliss-Shader/assets/29584262/6b76782e-c971-43e8-9156-453e92fb40bd)
Shader off below jungle:
![2024-06-21_19 15 33](https://github.com/X0nk/Bliss-Shader/assets/29584262/e083ec31-a172-4775-bd8b-2fcb5fe8c2a2)
Shader on below plains:
![2024-06-21_19 16 58](https://github.com/X0nk/Bliss-Shader/assets/29584262/22d3a42e-b9d9-4df3-bc83-6c9e3449b34e)
Shader on below jungle inside sodium settings menu:
![2024-06-21_19 20 02](https://github.com/X0nk/Bliss-Shader/assets/29584262/d8e2746d-0a75-4bec-aca4-9d636d0d5073)

### Describe how to reproduce the bug
Download the in-dev version of the shader (unsure if this also happens with modrinth/release version)
Leave everything at default
Locate a Jungle and go underground

**Comment by X0nk** [comment]
this has been improved, but it cant be fixed. i cannot stop fog from going indoors
