### ISSUE TITLE
Weird specs of light/fog seaming through when inside of caves

### ISSUE THREAD

**Issue by Contonia** [X0nk/Bliss-Shader#221]
![2024-06-24_21 29 58](https://github.com/X0nk/Bliss-Shader/assets/173732710/9887b154-9137-4e84-b037-06b8e062581c)
![2024-06-24_21 34 15](https://github.com/X0nk/Bliss-Shader/assets/173732710/5c4d00fa-6a9b-4f04-b6c8-31544dfca4c3)

These weird specs of light or fog keep seaming through certain areas when Im in a cave, whenever I disable volumetric fog it seems to be fixed but I still don't know why volumetric lighting/fog causes this.

I'm using distant horizons on 1.20.4 with sodium, iris, lithium, and indium on a rtx 3060. and even when disabling DH it still appears, still not sure how or why this happened.

**Comment by X0nk** [comment]
its just the shadowmap leaking through the wall a little. ill make sure the light leak fixes are working right

**Comment by Contonia** [comment]
Ah, that makes more sense, thanks!
