### ISSUE TITLE
Rain particles doesn't show through glass

### ISSUE THREAD

**Issue by Atlas020** [X0nk/Bliss-Shader#225]
As the title say's, the rain paticles don't appear when there is any type of glass in front of it (also rain fog)

![2024-06-27_21 54 57](https://github.com/X0nk/Bliss-Shader/assets/135953491/20d1c58f-de22-4f1b-ba2f-70b4097a24cf)
![2024-06-27_21 55 04](https://github.com/X0nk/Bliss-Shader/assets/135953491/85fab4f0-9659-45bf-a1ce-1b0888213f8a)

I've tried with both v2.0.4 and the latest in-dev version and they both have the same issue.
Also tried with complementary unbound and reimagined r5.2.1, kappa v5.2 and noble v1.6.7 and the bug is not there.

I removed all my mods exept for sodium and iris, and all resource packs to be sure it wasn't part of the issue.

**Comment by X0nk** [comment]
this is vanilla minecraft behavior. rain does not render behind translucent geometry.
bliss changes normal glass to be rendered in the translucent render layer, so it can have hardcoded reflections like water and the other glasses.
