### ISSUE TITLE
Specular water reflections rendering on top layer

### ISSUE THREAD

**Issue by CjPhoenix** [X0nk/Bliss-Shader#226]
The specular reflections of water are visible on top of all blocks, player hand, player model in 3rd person, etc.
![2024-06-28_11 14 24](https://github.com/X0nk/Bliss-Shader/assets/83119836/89248a98-ab41-4188-81bc-68c6de5d3a9c)

Using Distant Horizons, possible reason for error.

GPU: Nvidia RTX 3060 (mobile)
OS: Windows 11
MC Version: 1.20.1
Shader Loader: Oculus
Shader Version: Bliss Shader Main (In development version)

Some other mods in use: tetra, create, quark, biomes o' plenty.

Turning off "World > Water Settings > Specular Reflections for Water" is the only fix I have found.

**Comment by CjPhoenix** [comment]
Reset settings and issue was fixed.

**Comment by X0nk** [comment]
commenting because i know what it was; you turned overdraw prevention off. that's why it did that.
