### ISSUE TITLE
World/Screen too bright if auto-exposure is off

### ISSUE THREAD

**Issue by kylocat** [X0nk/Bliss-Shader#229]
World/Screen too bright if auto-exposure is off. However with auto-exposure on it will be diffcult to see at night with hand-held light.
![bliss_bug_2](https://github.com/X0nk/Bliss-Shader/assets/120186855/785dbd6c-e79e-432b-85c2-e97beb5a16c5)

**Comment by X0nk** [comment]
when auto exposure is off, you must set the manual exposure value. its not broken in this screenshot, the manual exposure is just set too high for that scene.

auto exposure exists to brighten dark scenes, and darken bright scenes, this is to sort of level out the lighting brightness range.
the lighting brightness range is very large between outdoors, and dark areas like caves or night time, so a single exposure value just cant do both situations well.

you can make night time brighter, by increasing moon illuminance `shader settings -> direct light -> moon illuminance`
and / or increasing minimum light levels, `shader settings -> ambient light -> minimum light`
