### ISSUE TITLE
Glitchy render of transparent blocks in End and Nether

### ISSUE THREAD

**Issue by HonestPorcupine** [X0nk/Bliss-Shader#23]
o7 love your work.
Version of shader: 2.0.4.
Fabric with Sodium+Iris on 1.20.1.

If you use TAA and Temoral Upscaling at the same time it renders transparent blocks (honey, slime, water, glass, glass panels, Nether Portal block etc.) in weird way. 

- This "bug" is appeared only in Nether and End dimensions.
- **TAA or Temporal Upscaling don't cause this. Yet only in combination.**

if you want more details I am open to help recreating this issue.
![Screenshot_2023-09-16_16-50-26](https://github.com/X0nk/Bliss-Shader/assets/101061284/18a5a0f6-0d03-45d3-b671-1d7d01148082)

**Comment by X0nk** [comment]
known issue. is actually fixed in the latest github commit, but not in the large release versions.
