### ISSUE TITLE
Translucent Water Particles?

### ISSUE THREAD

**Issue by Nekrozmik** [X0nk/Bliss-Shader#232]
I'm not sure how plausible this is, but using the shader I realized it was jarring seeing the difference between the translucent rain and the opaque bright blue particle splashes on the ground, and I was wondering if it was possible to incorporate a similar effect to the rain for certain water related particles?

**Comment by X0nk** [comment]
it is very difficult to narrow down what particle is what, as there is no way to identify them except using their color with the shader.
if i do some rough color thresholding stuff, other particles with similar color would get the effect, and if the resourcepack changes the color, it could ruin it all.

**Comment by Nekrozmik** [comment]
i see, fair enough
