### ISSUE TITLE
Handheld lighting inverted with FloodFill

### ISSUE THREAD

**Issue by splat15** [X0nk/Bliss-Shader#233]
### Describe the bug
The "HANDHELD_LIGHT_RANGE:" slider changes where handheld lighting starts instead of where it stops. this has the effect of having the light source light up the players surroundings in a fixed radius and then depending on the slider state much further out the light source brightens terrain.
https://github.com/X0nk/Bliss-Shader/assets/71266003/9a3bc0a9-0a8a-4459-96a2-87bce6230294

### Describe how your minecraft is set up
Minecraft 1.21 Fabric
Fabulously optimized modpack 1.21
Distant Horizons 1.21
![Screenshot (148)](https://github.com/X0nk/Bliss-Shader/assets/71266003/918a079d-1c80-42f3-a77c-0436b89b75f6)

### Describe how to reproduce the bug
The effects are easier to see with "Minimum Light Brightness" at 0. 
Turn on "Hand Held Light" and hold a light emitting item. 
The color of the emitted light has no effect on the far lighting.
Turn on FloodFill. 
Then turn "HANDHELD_LIGHT_RANGE" up.
https://github.com/X0nk/Bliss-Shader/assets/71266003/9a3bc0a9-0a8a-4459-96a2-87bce6230294

if a specific shader setting can make it start/stop bugging, please list what shader setting does that.
FloodFill, HANDHELD_LIGHTING_RANGE

**Comment by X0nk** [comment]
at the moment, HANDHELD_LIGHT_RANGE does not effect floodfill lighting. only default lighting,

its not actually changing where its starting, the handheld light range is simply farther than the floodfill lighting range.
floodfill lighting completely replaces the normal lightmaps, but outside its range, it goes back to normal lightmaps.
you are simply seeing the handheld light range of normal lighting go so far that it's visible outside the floodfill range. this is not intended and will be fixed.
