### ISSUE TITLE
TAA bug in the latest commit

### ISSUE THREAD

**Issue by LDAGgit** [X0nk/Bliss-Shader#239]
TAA artifacts/ trailing on DH terrain

https://github.com/X0nk/Bliss-Shader/assets/174941437/580a0d2f-f24b-4f54-9f57-abc72320f659

![2024-07-07_17 30 50](https://github.com/X0nk/Bliss-Shader/assets/174941437/3949355c-609c-498f-b0fb-23e0dbf4fcf6)

The artifacts started out of the box, and as soon as I started moving in my world, weren't present in the previous commits.
Staying still and panning/tilting does nothing, but moving in the x/y/z axis does, only on the DH terrain. 
Turning off TAA fixes it, but then there's no TAA :(

**Comment by X0nk** [comment]
yep this was just a small accident on my end, i cleaned up TAA code, and forgot to make it change for when DH was enabled.

its fixed now!
