### ISSUE TITLE
Feature request : add motion blur

### ISSUE THREAD

**Issue by Rasyamb** [X0nk/Bliss-Shader#24]
Will you add motion blur into shader?Because when i running shader,i only get around 40 - 50 fps,and when I run the shader there is no motion blur that look not smooth,but when I running motion blur on a shader that has motion blur, it looks smooth.

**Comment by X0nk** [comment]
it is a big maybe. i have been thinking about it.

**Comment by Lqi0** [comment]
I know it’s not worth much, but I second this

**Comment by meisme-dev** [comment]
I agree with this, I get a lot of micro stutter and motion blur would improve it quite a lot

**Comment by GazimSoliev** [comment]
Yes, add pls blur motion, it helps to improve low fps

**Comment by avc1657** [comment]
It took me a couple of minutes to realize the shader does not have motion blur, lol. I carefully looked through the menus just to find nothing. Please, add motion blur, it's good specially for players with lower fps or micro stuttering.

**Comment by X0nk** [comment]
has been added
