### ISSUE TITLE
Shaders don't work in nether

### ISSUE THREAD

**Issue by KolxozGG** [X0nk/Bliss-Shader#242]
- rtx3060ti
- Windows 11
- Fabric 1.20.1
- Iris
- Bliss Shader Main Commit 479

To reproduce just enter to the nether

composite2.fsh: composite2.fsh: 0(900) : error C1503: undefined variable "atmosphereGround"

![2024-07-08_15 24 32](https://github.com/X0nk/Bliss-Shader/assets/111286240/7b144cc2-b551-432d-8b80-37823c67d4c3)

**Comment by MomoDerDodo** [comment]
composite2.fsh: composite2.fsh: 0(830) : error C1503: undefined variable "atmosphereGround"

Same error till today.

**Comment by X0nk** [comment]
just turned the atmosphere ground back on in `shader settings -> world`

**Comment by MomoDerDodo** [comment]
For me it only works, if i turn that atmosphere ground setting off.
