### ISSUE TITLE
Transparent armor on Development version?

### ISSUE THREAD

**Issue by ardissaps** [X0nk/Bliss-Shader#243]
### Describe the bug
Describe the bug in as much detail as possible. capturing footage of it with images or videos is preferred.

### Describe how your minecraft is set up
1. Include a screenshot of the in-game f3 debug overlay. Please make sure it is fully visible.

2. If you cannot do option 1. Please list the following information instead:
- What GPU vendor you are using (e.g Apple/AMD/Nvidia/Intel)
- What operating system you are using (e.g Windows/Linux/macOS)
- What minecraft version you are playing (e.g 1.20.4, 1.16.5, 1.12)
- If you are using a special client for minecraft (e.g lunar, badlion, feather)
- What shader loading mod you are using (e.g Iris/oculus/optifine)
- What version of the shader you are using (e.g Bliss v2.0.4, Bliss Shader Main)
- If you are using any, what additional mods you are using besides the ones required to use the shader (e.g distant horizons, physics mod)

### Describe how to reproduce the bug
Show exactly how to make the bug appear, if you can. Video footage is preferred.

Isolate the bug. some multiplayer servers cause issues on their own. in a newly made singleplayer world, with default/reset shader settings, show the steps to cause the bug

if it is happening on content from a mod, list what mod, and what content of that mod it happens on.

if a specific shader setting can make it start/stop bugging, please list what shader setting does that.

**Comment by X0nk** [comment]
mate you didn't follow the template AT ALL

anyways.... thats a problem with the shoulder surfing mod, it messes with rendering a little, and it bugs out. i can't fix it on my end without turning off the proper rendering of translucent entities. you can find that setting in debug/experimental settings.
