### ISSUE TITLE
Shader darken EMI hud items. Is there a setting to prevent it ?

### ISSUE THREAD

**Issue by GiBoraD** [X0nk/Bliss-Shader#244]
here the example

iron tools shows better

1.20.1 version if needed

with Shader:
![with_Shader](https://github.com/X0nk/Bliss-Shader/assets/102690428/62540c79-08c5-4b50-bc17-d2fa9fae1cbd)

without Shader:
![without_Shader](https://github.com/X0nk/Bliss-Shader/assets/102690428/f941606f-0fb2-4074-bfca-51d7b43db146)

**Comment by X0nk** [comment]
the shader cannot intentionally influence the GUI at all. this is probably an iris problem or a EMI mod problem
