### ISSUE TITLE
bug with physics mod

### ISSUE THREAD

**Issue by Ray-Dieterich** [X0nk/Bliss-Shader#25]
when working with the physics mod (  the compatibility button is on  ), the particles will be rendered incorrectly. (  just like mosaic  )

**Comment by Endri2015** [comment]
me too

**Comment by Macintosh-Fan** [comment]
Me too, and it's not an issue with the original Chocapic shader.
<img width="473" alt="image" src="https://github.com/X0nk/Bliss-Shader/assets/50642934/d33039ab-f83e-40b8-8e35-0ffe42d46574">

**Comment by X0nk** [comment]
physics mod support is planned to be dropped.

it has so many confusing, incomprehensible issues that i don't even know where to start to fix a bunch of them, and i really really don't want to make 30 small patches all over the place that could break in the next physics mod update.

haubna could have made supporting their mod comprehensive, but they did not. it's up to them to make it even possible for shaders *other than complementary* to completely support their mod.
