### ISSUE TITLE
Glass and Water

### ISSUE THREAD

**Issue by PotatosForLife** [X0nk/Bliss-Shader#250]
![2024-07-19_13 57 47](https://github.com/user-attachments/assets/56aaa261-08ae-4c94-be48-16737076c6b1)

Anyone know how to fix this?
the water becomes see through when I put glass next to it, causing me to see the sky and top of the water

**Comment by X0nk** [comment]
this is most likely just sodium's lack of translucent sorting causing it. i cannot fix it, but you *can* make glass not render as translucent. just go inside the shader, find the `block.properties` file, and delete the entire line at the top that starts like `layer.translucent`
