### ISSUE TITLE
The water is completely transparent through the glass | water bumps under transparent blocks

### ISSUE THREAD

**Issue by Ultra119** [X0nk/Bliss-Shader#255]
If you put the glass block next to the water, at some angle the water haze is not rendered

![huge_2024-07-24_19 41 32](https://github.com/user-attachments/assets/9ed0a03a-e228-4328-90ac-b6d4581bf76b)

> just noticed closed PR about that, sorry

Suggestion:
Also noticed that water bumps are rendered even if there are transparent blocks directly above the water (Any blocks, I suspect). It looks, of course, not very good when waves are layered on ice or glass

**Comment by X0nk** [comment]
the water not rendering is because sodium has no translucent sorting. thats it. i cannot fix it. 

not to fear though, the next major release of sodium will have translucent sorting and it will stop happening.
