### ISSUE TITLE
Landscape printed to horizon

### ISSUE THREAD

**Issue by OxoGhost01** [X0nk/Bliss-Shader#263]
### Describe the bug

Tbh i'm not familiars with mods and shaders. So maybe i set something wrong. The bug is : when i look around, the mountains, village etc stay in the horizon like an old game bug, you can see it in the video, maybe i did something wrong, but i think it's a bug x)

And here, the video (i can make an other one if you want)
https://streamable.com/lcjwqj (tell me if that doesn't work, it's the first website i found to upload videos XD)
(or tell me how to do it in another way, the video is 50Mb, github said 10Mb, and the website said "link will expire in 2 days TT.TT)

### Describe how your minecraft is set up
Here is the F3 screenshot :
<img width="1280" alt="2024-08-01 17_53_59-Minecraft_ 1 21 - Singleplayer" src="https://github.com/user-attachments/assets/7e2175fa-4477-4672-8609-2595ff2a2e6c">

### Describe how to reproduce the bug
idk i just moved lmao

Oh yeah, that might help : i'mtrying to use the mod distant horizon :/

Thank you for your help !

**Comment by OxoGhost01** [comment]
okey hummm, i just think my pc isn't enough powerful to support all of this...

**Comment by X0nk** [comment]
try restarting the game,
or Go to `Distant horizons settings -> advanced options -> graphics -> rendering -> change transparency to complete`
also The "Alex's caves" mod can also cause this. disable `Biome Ambient Light Coloring` in the alex's caves mod config
