### ISSUE TITLE
Tall waving plants should have whole plant wave, not just the top-half

### ISSUE THREAD

**Issue by Macintosh-Fan** [X0nk/Bliss-Shader#264]
It would look less weird if the entirety of tall plants could go in a waving motion, not just the top-half.
<img width="570" alt="A tall waving plant with only the top-half waving." src="https://github.com/user-attachments/assets/6abb4d32-6466-4481-bcb7-3aeb4286241f">

**Comment by X0nk** [comment]
how old is your bliss version? because i improved tall waving plants a while ago

**Comment by Macintosh-Fan** [comment]
Oh yeah, I just used the "released" version of the shader.
