### ISSUE TITLE
Rain puddles are not working

### ISSUE THREAD

**Issue by abenn13** [X0nk/Bliss-Shader#265]
Turning rain puddles option on does not create rain puddles when it starts raining. Am I missing something? I've spent a good amount of time kind of wondering around the shader options before coming here trying to solve my own problem now I am out of ideas lol; TIA good shader highly recommend!

2. Nvidia 4090; i9-13900k
- Windows 11
- Minecraft 1.21
- Iris shader loader
- Using most recent Bliss version available on Modrinth
- continuity ; entity textures and entity features ; sodium ; Xaeros minimap ; fabric (obviously) ; sound physics remastered ; indium ;

**Comment by X0nk** [comment]
you need to enabled specular reflections `shader settings -> resourcepack support -> specular reflections`
