### ISSUE TITLE
Sky going black when I'm not outside

### ISSUE THREAD

**Issue by nehhhf** [X0nk/Bliss-Shader#267]
When ever I'm far back enough in this tunnel, the sky outside goes black until I go back within about 10 blocks of the door, I don't have any mods that change the skybox or anything that I think could be messing with it. I tested it with other shaders and Bliss is the only one that does this.
![2024-08-04_10 37 51](https://github.com/user-attachments/assets/408120f1-3ed6-4ccd-881b-aad732c1dcc4)

https://github.com/user-attachments/assets/5940cf3e-b8a6-4e9c-93de-fd38fe2ece3f

**Comment by X0nk** [comment]
this is "cave fog" blotting out the sky in low sky light level. you can disable it in `shader settings -> fog settings -> cave fog`
