### ISSUE TITLE
weird visual bug underwater

### ISSUE THREAD

**Issue by Zaid-isis** [X0nk/Bliss-Shader#269]
Basically. If you build a glass house underwater and put a sponge in it to remove all the water.when you see through the Glass.The underwater fog disapears but the lightning is still there

https://github.com/user-attachments/assets/a63b8b0c-5e5f-4e65-8495-e9099b559192
https://github.com/user-attachments/assets/0765525d-f101-48a4-8e1e-9a135a894162

**Comment by joshua-igor** [comment]
That happens because Iris does not have Alpha Sorting so it is not possible for Bliss to fix this at the moment. Future versions of Iris are expected to come with Alpha Sorting turning this bug fixable.

**Comment by Rikunosukee** [comment]
This might happen for Iris version because bliss was made for optifine yet not optimized for iris

**Comment by X0nk** [comment]
no, it's exactly as the comment above yours says. it's just sodium lacking a feature, which us coming in sodium v0.6+ so it's not much of a problem.

**Comment by MichMich003** [comment]
Hi, i am not very fluent with the shader technical stuff, but is this the same bug that will be fix in sodium v0.6+ ?
Thx four your answer =)

![2024-08-29_18 35 59](https://github.com/user-attachments/assets/a6947f7f-51d9-4150-a26e-293e1db2a6fa)
![2024-08-29_18 35 59](https://github.com/user-attachments/assets/4bd0c470-ea17-4ad4-8c7a-7ecc8154f44b)

**Comment by X0nk** [comment]
yes, sodium 0.6 or newer will not have this problem anymore.
