### ISSUE TITLE
Not Supported anymore by the latest distant Horizons.

### ISSUE THREAD

**Issue by ExpertMedal7** [X0nk/Bliss-Shader#270]
DH chunks not loading with the latest 1.21 version and bliss.

Version 1.21
Sodium-NeoForge-0.6.0+mc 1.21
Iris-NeoForge-1.8.0+1.21
Distant Horizons-NeoForge-2.13-a-dev-1.21

According to DH devs,Bliss will need to be updated to support the new versions for now.
![IMG_4037](https://github.com/user-attachments/assets/27f42078-86af-4171-bf43-985b1abdb6dd)
![IMG_4038](https://github.com/user-attachments/assets/dfbde634-910c-4a45-bcf1-fc747a6a70d8)
![IMG_4037](https://github.com/user-attachments/assets/51a87972-d9c2-4f22-93fc-693e3327aebc)

**Comment by joshua-igor** [comment]
The same is happening with me since DH bumped up the Iris version requirement.

**Comment by ExpertMedal7** [comment]
Ya looks like we’ll have to wait for an update

**Comment by X0nk** [comment]
guess i'll have to get those new programs working

**Comment by ExpertMedal7** [comment]
Thank you

**Comment by joshua-igor** [comment]
> guess i'll have to get those new programs working

I really appreciate it!

**Comment by fayer3** [comment]
did some testing, this seems to be an iris bug on neoforge, when the shader is already loaded on startup. Reloading the shader once in a world should fix the issue.

**Comment by ExpertMedal7** [comment]
Yep it seems to be working.Thank you!

**Comment by Rachid90** [comment]
Hello, I have the same issue. I have iris v1.8.8, DH v2.3.0, bliss v2.0.4. Did you find a fix?

**Comment by X0nk** [comment]
v2.0.4 and older do not have distant horizons support. as the modrinth/curseforge pages stated.
you need the in-development version of bliss. read the README page of this github
