### ISSUE TITLE
There's a slight jitter around my skin only when I move.

### ISSUE THREAD

**Issue by ayv123** [X0nk/Bliss-Shader#273]
It looks the same if I'm walking too. The only thing I changed in the settings was some of the season settings and the fog. 
(Sorry. The video quality died)
https://github.com/user-attachments/assets/e82d7353-9faf-4a2e-bd3a-585a1052f367

**Comment by X0nk** [comment]
this is... normal, unfortunately. its artifacts from TAA. temporal upscaling makes the artifact significantly worse, and the lower your fps the worse it is.
