### ISSUE TITLE
Strange cloth physics texture with Physics Mod

### ISSUE THREAD

**Issue by ShrikerChestTree** [X0nk/Bliss-Shader#28]
When I enable cloth physics (banner), a strange texture appears (even if I enable Physics Mod Support). 
Please fix it in the next version.

**Comment by X0nk** [comment]
what version are you using when doing this? the latest github commit or v2.0.4????

**Comment by ShrikerChestTree** [comment]
> Owner

This was on version 2.0.4 and higher

**Comment by Amras27** [comment]
Hi. Same for me with the version 2.0.4 and the last on Github.

**Comment by ShrikerChestTree** [comment]
> 我的也是的
*Translation: Mine too

**Comment by X0nk** [comment]
physics mod fixed their stuff and this should work now
