### ISSUE TITLE
X-ray effect in circle around player

### ISSUE THREAD

**Issue by Boyownik** [X0nk/Bliss-Shader#280]
### Describe the bug
X-ray effect in circle around player. It is moving as player moves. When player moves for a bit in same place this glitch is gone or atleast reduced to few blocks.

![2024-08-20_16 19 14](https://github.com/user-attachments/assets/9d63f13e-8414-413e-a6ad-3a97feda0a82)

### Describe how your minecraft is set up
![2024-08-20_16 21 14](https://github.com/user-attachments/assets/a8897af4-d197-47f9-b3d1-46a8f01442a3)

**Comment by joshua-igor** [comment]
This does not look like a Bliss Shader bug, this looks like a Distant Horizons misconfiguration. try to reset everything to default and see if this solves the issue.

**Comment by X0nk** [comment]
nah. this is normal.
this is the shader-side "overdraw prevention" 
it always sits at 1 chunk less than your render distance. but nobody has a pc strong enough to load minecraft chunks fast enough to hide it.

solution: `shader settings -> supported mods -> distant horizons -> max overdraw prevention distance` set it to something like 8 chunks or whatever.
