### ISSUE TITLE
无论如何都无法开启大积云，不管是关闭还是开启每日天气，体积云是否开启

### ISSUE THREAD

**Issue by S-1-5-21-1726115** [X0nk/Bliss-Shader#283]
标题已经描述了我的问题

**Comment by X0nk** [comment]
我使用的是翻译器，如有任何问题，请见谅。

你使用的是哪个版本的着色器？是 “bliss-shader-main” 还是 "bliss v2.0.4”?

**Comment by S-1-5-21-1726115** [comment]
测试版,就是直接从“Download ZIP那里下载的”


不过我可能要等一个星期才可以回复了







                       
原始邮件
                       
                     

发件人："Xonk"< ***@***.*** &gt;;

发件时间：2024/8/27 6:45

收件人："X0nk/Bliss-Shader"< ***@***.*** &gt;;

抄送人："S-1-5-21-1726115"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [X0nk/Bliss-Shader] 无论如何都无法开启大积云，不管是关闭还是开启每日天气，体积云是否开启 (Issue #283)




 
我使用的是翻译器，如有任何问题，请见谅。
 
你使用的是哪个版本的着色器？是 “bliss-shader-main” 还是 "bliss v2.0.4”?

**Comment by S-1-5-21-1726115** [comment]
终!于!修!了!!!!!!!!
