### ISSUE TITLE
Render clouds as fog disables shaders

### ISSUE THREAD

**Issue by OsChD** [X0nk/Bliss-Shader#284]
### Describe the bug
The bug only appears when I try to enable the render clouds as fog settings and completely disables my shaders
I am using DH and removing it helps but this is not what i want.

### Describe how your minecraft is set up
1. Include a screenshot of the in-game f3 debug overlay. Please make sure it is fully visible.

2. If you cannot do option 1. Please list the following information instead:
- Nvidia RTX 3070
- W11
- 1.20.4
- Minecraft launcher with fabric loader
- Iris
- Bliss-Shader-Main.zip *edit*

### Describe how to reproduce the bug
To reproduce it all i have to do is enable the renderring of clouds as fog to get an error in the chat.
This disables the shaders and prompts to contact the shader developer.
(edit) I tried download using the code button, the absolute latest version and it seemed to have fix it.

 deferred.fsh: deferred.fsh: 0(753) : error C1503: undefined variable "sh2"
0(753) : error C1503: undefined variable "sh2"

![Screenshot_1](https://github.com/user-attachments/assets/afc1957d-8d88-44ed-badf-eb184a2b6a00)
![Screenshot_2](https://github.com/user-attachments/assets/3f093972-9355-48c8-aa3e-c0085b451428)
![Screenshot_3](https://github.com/user-attachments/assets/3002b4ba-df3b-47f6-9158-dba400dad2b8)
![image](https://github.com/user-attachments/assets/fdf0f012-11ce-434e-b643-803c2988eb1b)
![image](https://github.com/user-attachments/assets/3a348736-cb18-48c8-a563-3ce9c09b71fd)
![image](https://github.com/user-attachments/assets/576b097b-367f-4076-ba37-00443e1c6509)
![image](https://github.com/user-attachments/assets/1c10e844-59ab-4293-96ba-97c056efd4bd)

**Comment by OsChD** [comment]
> My account has been stolen, and they send junk emails everywhere. I've changed my password. Sorry for what you've received. 1sopropanol

No problem lol,

**Comment by X0nk** [comment]
ok, since i fixed it in a later update i guess its all good now lol
