### ISSUE TITLE
Rendering errors related to DistantHorizon -2.2.0-a-1.21.1-no-fabric

### ISSUE THREAD

**Issue by kick-system** [X0nk/Bliss-Shader#287]
### Describe the bug
In the 1.21.1 version, when using DistantHorizons-2.2.0-a-1.21.1-neo-fabric and Bliss-Shader-main together, grass blocks covered with snow and leaves covered with snow render incorrectly in the lod block, appearing bright blue
![无标题](https://github.com/user-attachments/assets/a62e00a7-3783-4e1d-9365-8f0464067d8b)
![无标题1](https://github.com/user-attachments/assets/f1efb088-a208-40a8-addb-252db0108cab)
The second image uses Bliss Shader main, while the first image uses other Shaders
shader setting:
[Bliss-Shader-main.zip.txt](https://github.com/user-attachments/files/16760608/Bliss-Shader-main.zip.txt)

### Describe how your minecraft is set up
GPU:Intel(R) Iris(R) Xe Graphics
Windows-11 Version:23H2
Minecraft version:1.21.1
Mods：DistantHorizons2.2.0a
Shader loader:iris-fabric-1.8.0-beta.3+mc1.21.1

**Comment by X0nk** [comment]
disables the "seasons" effect. its kinda hard to control this effect on the distant horizons terrain. so it kinda messes up sometimes...
