### ISSUE TITLE
Don't default settings look too bad?

### ISSUE THREAD

**Issue by EQQx110** [X0nk/Bliss-Shader#290]
Every time I download a new version I have to change the settings to make it look more like an older version because the new default looks too bad to me.

Default:
![2024-08-29_14 17 13](https://github.com/user-attachments/assets/d7954aeb-6ae1-4f33-a19c-44144dee5452)

My settings:
![2024-08-29_14 17 35](https://github.com/user-attachments/assets/fdb198e7-0c1f-42f8-80e1-284d815ace2a)

This is my settings file content for who wants to use them:

shadowDistance=256.0
SHARPENING=1.0
TORCH_B=0.01
AmbientLight_R=1.1
POM_DEPTH=0.30
sss_density_multiplier=2.0
SSS_TYPE=2
Specular_Reflections=true
POM=true
TONEMAP=Tonemap_Xonk
SKY_CONTRIBUTION_IN_SSRT=true
AmbientLight_G=1.1
LPV_ENABLED=true
AmbientLight_B=0.8
TORCH_G=0.5

**Comment by X0nk** [comment]
i'm glad you could get it looking how you want with the settings.
The style of bliss changes over time, as my goals for how it should look evolve. whether it looks good or bad is up to you.

**Comment by WoMspace** [comment]
Swiggety swances, you can copy settings files between instances

**Comment by EQQx110** [comment]
> i'm glad you could get it looking how you want with the settings.
I'm glad too, good job making the settings.

>The style of bliss changes over time, as my goals for how it should look evolve. whether it looks good or bad is up to you.
While I made some stylistical more personal changes, like the tonemap and the torches, I find some other default settings objectively worse, like the sharpening turned off, making everything too blurry. Then of course it's your shader and you decide, just wanted to make you notice.

> you haven't really asked a question though, it was more of a statement of your opinion lol
You're right, I should have put this in suggestions, my bad.


> Swiggety swances, you can copy settings files between instances
Great, didn't know that. I don't play Minecraft often so I assumed the settings wouldn't be compatible between different verisions.
