### ISSUE TITLE
Torches in multiplayer

### ISSUE THREAD

**Issue by DudeMcChill** [X0nk/Bliss-Shader#292]
I am not sure the terms of certain things, or even if the shader is meant to be multiplayer compatible, but when it comes to the feature where when you're holding a torch or other light source and it lights up the surrounding area, is there a way to make it so you can see other players doing that too? or is that not a feature/ a bug?

**Comment by X0nk** [comment]
With the "floodfill" setting `shader setting -> ambient light -> floodfill` it may be possible
otherwise, I only can reliably find the player position, i have absolutely zero information about where or what any other thing in the world is.

**Comment by S0ly** [comment]
please reopen its still an issue

**Comment by S0ly** [comment]
@X0nk

**Comment by X0nk** [comment]
this was not an issue or bug report. they were simply asking a question

**Comment by S0ly** [comment]
can we make that an issue please ? it would be really cool to see others hindsight

**Comment by DudeMcChill** [comment]
hey actually, i had done some testing and found out that zombies and other mobs will emit light properly when holding a torch, so i went into the files and rendered players the same and it works! I haven't encountered any issues caused by this and just thought I would tell you, and anyone else who reads this thread.

**Comment by DudeMcChill** [comment]
@S0ly if read my comment above if you'd like to see others handlight!!

**Comment by S0ly** [comment]
yes please make a pull request about it :)
