### ISSUE TITLE
Character is Glitched out in third person

### ISSUE THREAD

**Issue by ARandomPlayer2** [X0nk/Bliss-Shader#293]
I was testing out Bliss shaders with Distant horizons and got it looking amazing, however when i finally got what i wanted. 
However, I went into third person and my character is completely bugged.

![image](https://github.com/user-attachments/assets/afb177b5-f906-4516-a182-a12919fda326)

![image](https://github.com/user-attachments/assets/6bf4e374-b6d3-4945-94c6-e16dde114012)

I'm sorry to say I'm not sure what happened, I didn't notice this bug all the way up until I was preparing to return to my survival world and noticed it last second. 
I am not sure what bugged out here or what settings I changed to do this- is this a common issue? Or should I try getting a new version? It looks as if it has a lot of Z-fighting happening, and both images are showing the front view of the character. My first-person arms are not having this issue.
 and I do have three mods installed that could change the character, I have Better Combat, 3d skin layers, and shoulder surfing. I'm on 1.20.1 fabric with a bunch of performance mods installed (280 mods including preformance).

**Comment by DovahMid** [comment]
I've had a similar issue which i reported a few days ago with light leak fix not working on my character .
I thought to add it here just for the sake of collection
![2024-09-02_05 57 42](https://github.com/user-attachments/assets/a84792a4-c0f1-4605-a912-5feb73f89306)
I could replicate this with only :
MC 1.21.1 + Fabric 0.16.3
Iris 1.8.0-beta.3
Sodium 0.6.0-beta.1
DH 2.2.0-a
Using the latest github .zip download (Commit #482) using all default settings except for Old-Light_Leak_Fix set to true
Graphics settings at max except for minecraft render distance at 8 chunks and no Fog culling

**Comment by X0nk** [comment]
shoulder surfing conflicts with iris's [hybrid deferred rendering for entities](https://github.com/IrisShaders/ShaderDoc/blob/master/iris-features.md#hybrid-deferred-entities)

there are 2 ways to work around the issue:
- A: change the shoulder surfing mod config parameter adjust_player_transparency and set it to false
- B: turn off TRANSLUCENT_ENTITIES in shader settings -> debug/experimental

option A will make the camera kinda annoying in tight spaces.
option B will make all entities that were once see-through, completely opaque, and no longer see-through.



as for the light leaking issue, i have yet to look into it. no need to repeat-send it.

**Comment by ARandomPlayer2** [comment]
Thanks so much! I've been trying to figure that out ever since i set the post! It was the experemental settings, it looks like shoulder surfing didnt have anything to do with it

**Comment by X0nk** [comment]
it is 100% confirmed that shoulder surfing is the cause of the problem, due to how it slightly changes rendering, and how iris responds to the change.
