### ISSUE TITLE
Light does not seem to properly pass through glass blocks

### ISSUE THREAD

**Issue by ran4na** [X0nk/Bliss-Shader#294]
### Describe the bug
Describe the bug in as much detail as possible. capturing footage of it with images or videos is preferred.

![2024-09-06_18 13 38](https://github.com/user-attachments/assets/8584d633-68b2-4f81-ab59-aac590a4fba7)
![2024-09-06_18 13 46](https://github.com/user-attachments/assets/799cb667-d171-438f-993c-f8d3659bef9a)
![2024-09-06_18 13 25](https://github.com/user-attachments/assets/886dfdb0-3b5c-4175-b8f0-5b3b3641411a)

Direct sunlight can't seem to pass through glass blocks (in addition to glass panes, and both of their stained varieties) at all. Instead, all surfaces behind glass are only lit with ambient light, which (I assume unintentionally) dulls down a lot of indoor scenes. If this is intentional, I think an option to enable lighting through glass would be nice, as I've seen this listed as a previously closed issue on here and as a feature in Chocapic shaders.

### Describe how your minecraft is set up
1. Include a screenshot of the in-game f3 debug overlay. Please make sure it is fully visible.
![2024-09-06_18 14 01](https://github.com/user-attachments/assets/599d59b4-a6fa-419e-b5a6-0d5d3445afd7)
(Running on Windows 11)

### Describe how to reproduce the bug
Show exactly how to make the bug appear, if you can. Video footage is preferred.

- Turn off daily weather, clouds/cloud shadows and adjust other settings in order to see direct sunlight and stronger shadows (for visibility's sake)
- Place glass blocks or glass panes
- The blocks behind the glass are treated as if they're in shadow

The screenshot above was tested on a newly made singleplayer world and a clean minecraft 1.20.4 fabric instance. There are changes made to the shader settings to easily reproduce the bug, as the lighting appears very cloudy and diffuse by default.

**Comment by X0nk** [comment]
this issue has been fixed in the in-development version.
so youll have to use that version, or wait for a new release, whenever i do that...
