### ISSUE TITLE
bug when joining a different world on servers

### ISSUE THREAD

**Issue by Enndal** [X0nk/Bliss-Shader#296]
### Describe the bug
Describe the bug in as much detail as possible. capturing footage of it with images or videos is preferred.
the shaders stop working when joining a different world. it works fine in one but breaks in the other

### Describe how your minecraft is set up
1. Include a screenshot of the in-game f3 debug overlay. Please make sure it is fully visible.
I am using Fabric with a decent set of mods but who shouldn't (I think) interfere with it
![2024-09-08_11 28 34](https://github.com/user-attachments/assets/c0e013e6-1657-4246-be1b-8371584de3fb)
![2024-09-08_11 28 51](https://github.com/user-attachments/assets/ffb66a27-6016-4cb0-859f-1fe00f3d009f)

2. If you cannot do option 1. Please list the following information instead:
- What GPU vendor you are using (e.g Apple/AMD/Nvidia/Intel)
- What operating system you are using (e.g Windows/Linux/macOS)
- What minecraft version you are playing (e.g 1.20.4, 1.16.5, 1.12)
- If you are using a special client for minecraft (e.g lunar, badlion, feather)
- What shader loading mod you are using (e.g Iris/oculus/optifine)
- What version of the shader you are using (e.g Bliss v2.0.4, Bliss Shader Main)
- If you are using any, what additional mods you are using besides the ones required to use the shader (e.g distant horizons, physics mod)

### Describe how to reproduce the bug
Show exactly how to make the bug appear, if you can. Video footage is preferred.

it's as simple as said above with pictures. 

Isolate the bug. some multiplayer servers cause issues on their own. in a newly made singleplayer world, with default/reset shader settings, show the steps to cause the bug

_I cannot reproduce this in singleplayer I am afraid_

if it is happening on content from a mod, list what mod, and what content of that mod it happens on.

if a specific shader setting can make it start/stop bugging, please list what shader setting does that.

_I am not aware of any that can cause this_

**Comment by X0nk** [comment]
duplicate issue of [issue #275](https://github.com/X0nk/Bliss-Shader/issues/275l)
there is an explanation and solution in that issue, so it would be good to go read

**Comment by Enndal** [comment]
thanks for helping, but how do you enable clouds from here or fog? that still doesn't work it seems.
