### ISSUE TITLE
Outer end sky flashing

### ISSUE THREAD

**Issue by Endri2015** [X0nk/Bliss-Shader#30]
I am using better end mod, and the outer end islands sky does not work well.

https://github.com/X0nk/Bliss-Shader/assets/88259157/480ac11f-ce84-47ce-9aa2-052759473726

**Comment by X0nk** [comment]
my friend.... that's lightning flashing. it's intentional, but admittedly, unfinished.

**Comment by Endri2015** [comment]
are you done redoing the end?

**Comment by X0nk** [comment]
no
