### ISSUE TITLE
Cloud resolution slider does nothing

### ISSUE THREAD

**Issue by tritri301** [X0nk/Bliss-Shader#301]
Moving the cloud resolution slider does nothing and the clouds stay pretty blury, I don't have the "render as fog" option and I tried both in single player and multiplayer. I use DH, I have no idea if thew issue persist without

0.1 resolution clouds with F3
![2024-09-22_22 26 08](https://github.com/user-attachments/assets/55946335-6c14-413c-b6a9-8f9a2cb75e5a)

1.0 resolution clouds
![2024-09-22_22 26 23](https://github.com/user-attachments/assets/b63ad357-6abb-417d-93f5-f6ecde4f0c59)

**Comment by X0nk** [comment]
i am aware of this. this is the result of internal changes i have been doing. the fog resolution slider controls it now.
not very intuitive, i know. 

clouds are going to have alot less artifacts and will have way higher clarity soon.

at the moment, they are blurred so badly that its almost indistinguishable from 0.25x the window resolution when its actually rendering at 0.5x the window resolution. thats horrible lol
