### ISSUE TITLE
Terrain flickering issue with distant horzions

### ISSUE THREAD

**Issue by jtocash** [X0nk/Bliss-Shader#302]
terrain flickering with distant horizons version 7. Most notably it still occurs when paused.

https://youtu.be/Lor2g4MKN4k , watch at a higher resolution the flickering is harder to see on lower res

Default settings (tried to show, video cut off). it was a fresh install of the shader

occurs with these mods:
DistantHorizons-2.1.0-a-1.20.1.jar
fabric-api-0.92.2+1.20.1.jar
ferritecore-6.0.4-fabric.jar
indium-1.0.30+mc1.20.4.jar
iris-1.7.0+mc1.20.1.jar
lithium-fabric-mc1.20.1-0.11.2.jar
sodium-fabric-mc1.20.1.jar
tectonic-fabric-1.20-1.2.4-lib.jar
Terralith_1.20.x_v2.5.4.jar

I see videos online of this shader working with these mods so i dont think any of the mods are to blame

**Comment by X0nk** [comment]
its just TAA
