### ISSUE TITLE
Issues with DH beacons

### ISSUE THREAD

**Issue by simplynoni** [X0nk/Bliss-Shader#303]
### Describe the bug
Beacons rendered by Distant Horizons will have weird cyan and magenta colors when they should just be white.
![2024-09-25_19 20 39_4](https://github.com/user-attachments/assets/a5851e5e-2743-4e68-8fb1-eb3574df799f)
![2024-09-25_19 16 30](https://github.com/user-attachments/assets/6683c008-787e-4477-a1ae-a85876a21036)

### Describe how to reproduce the bug
Look at a beacon that is outside of the default Minecraft render distance.

**Comment by X0nk** [comment]
distant horizons added new shader programs which i have not yet added. this is simply the result of no special handling. 
it will be fixed in the next commit

**Comment by X0nk** [comment]
i have added these programs in the unstable-development branch, [if you want to try it](https://github.com/X0nk/Bliss-Shader/tree/unstable-development)

it should be coming to the main branch soon-ish
