### ISSUE TITLE
low health effect when a full hp with lowered max hp

### ISSUE THREAD

**Issue by sakari119** [X0nk/Bliss-Shader#306]
### Describe the bug
A red screen edge appears when max health of the player is lower than normal.
![image_2024-10-03_205446252](https://github.com/user-attachments/assets/8ebc01c3-8e94-42c6-b1e2-f7e2a87bba41)

### Describe how your Minecraft is set up
Fabric + iris + DH 2.1.2 + Latest main (mc version 1.2.1)

### Describe how to reproduce the bug
Set Max max health to eg: 6ph (3 hearts) on latest main download.

**Comment by X0nk** [comment]
this is not a bug. having a mod force health to be so low is just unexpected/unpredictable behavior.

you can turn this effect off in `shader settings -> post processing -> gameplay effects`
