### ISSUE TITLE
Cracks in blocks glow when breaking blocks

### ISSUE THREAD

**Issue by cjtonkin** [X0nk/Bliss-Shader#307]
When breaking blocks, the cracks that appear when the block is in the process of breaking glow bright white.
![2024-10-04_21 01 46](https://github.com/user-attachments/assets/55067178-4a24-431f-83dc-d9971bf1ce03)
![2024-10-04_21 01 07](https://github.com/user-attachments/assets/f93e169b-03c3-4bc4-bbfe-f35bd3cef15a)

AMD Radeon RX 7600 XT
Windows 11
Minecraft version 1.21.1
Iris ver 1.7.3
Bliss v2.0.4

Other mods installed:
-sodium 0.5.11
-lithium 0.13.1
-tectonic 2.4.1a
-fabric-api 0.105.0

It's definitely a problem with the shaders because when I disable them the problem disappears.

**Comment by X0nk** [comment]
this is just a problem that came around when iris changed the behavior of the lightmap coordinates in the shader program responsible for the cracking effect. 

there is no fix; you will just have to use a newer bliss version where i redid how that effect was handled. download the in-development version [from the main github area (read the description there)](https://github.com/X0nk/Bliss-Shader)

**Comment by thimblebird** [comment]
i almost feel like this issue in particular should be linked in the mod description. was tweaking all settings until giving up and looking for a solution here 🐢
