### ISSUE TITLE
[Bug] Memory Leak when using TACZ

### ISSUE THREAD

**Issue by TqLxQuanZ** [X0nk/Bliss-Shader#308]
### Describe the bug
Describe the bug in as much detail as possible. capturing footage of it with images or videos is preferred.

### Describe how your minecraft is set up
1. Include a screenshot of the in-game f3 debug overlay. Please make sure it is fully visible.

2. If you cannot do option 1. Please list the following information instead:
- What GPU vendor you are using: 
Nvidia RTX 3070
- What operating system you are using: 
Windows 11
- What minecraft version you are playing: 
Minecraft 1.20.1-forge.47.3.0
- If you are using a special client for minecraft: 
Only minecraft launcher
- What shader loading mod you are using: 
Oculus 1.7.0 and Embeddium 0.3.31
- What version of the shader you are using: 
Bliss Shader Main, directly downloaded from GitHub
- If you are using any, what additional mods you are using besides the ones required to use the shader:
[Timeless and Classic Zero 1.0.3](https://www.curseforge.com/minecraft/mc-mods/timeless-and-classics-zero)

### Describe how to reproduce the bug
1. Install those following mods:
Embeddium
Oculus
TACZ 1.0.3
2. Make sure bliss shader is on.
3. Create a new world.
4. Take out a gun, and start shooting, even without shooting the memory leak will also slowly piles up, shooting makes it faster for some reason.
5. Wait until the game starts to lag out.
6. Crash.

### Crash logs:
[crash-2024-10-06_00.01.16-client.txt](https://github.com/user-attachments/files/17266781/crash-2024-10-06_00.01.16-client.txt)

[crash-2024-10-06_00.08.19-client.txt](https://github.com/user-attachments/files/17266791/crash-2024-10-06_00.08.19-client.txt)

More Details:

This is within the single player mode, multiplayer also having the same when joining a dedicated server.
Problem doesn't exist with other shaders as far as I tested, such as complimentary shader.

Shader settings are default.

If this is an issue from TACZ itself, please let me know and I'll poke them in the issue thread.
https://github.com/MCModderAnchor/TACZ/issues/268

**Comment by X0nk** [comment]
this is indeed on TACZ's end, according to the Iris developer. 
it is a problem related to how the 2 mods interact when iris's [hybrid deferred entities](https://github.com/IrisShaders/ShaderDoc/blob/master/iris-features.md#hybrid-deferred-entities) feature is used by a shader. i cannot do anything about this.

there is an option in the shader you can turn off: `shader settings -> debug/experimental -> TRANSLUCENT_ENTITIES`
which turns off the use of that iris feature, but it will no longer render translucent entities correctly.

**Comment by TqLxQuanZ** [comment]
Alright, huge thanks on this, I'll poke on the TACZ developer side.

**Comment by X0nk** [comment]
im *very* confident in saying theyre aware of it. it has been months.

**Comment by TqLxQuanZ** [comment]
Damn that's quick reply haha, since you're here may I ask any idea of the estimation of releasing the DH supported version to CF?

**Comment by X0nk** [comment]
hmmm... i cant really say. ive got a handful of stuff i really want to fix up before then.
on top of that, burnout and motivation/focus problems add even more delays lol

**Comment by TqLxQuanZ** [comment]
I see, no worries on that! I really love to use your shader as it brings outstanding and amazing view, while retain the performance optimization from what I see.

**Comment by TqLxQuanZ** [comment]
Do you perhaps have a paypal donation page? The one on the github page right now is stripe only and doesn't allow paypal :(

**Comment by X0nk** [comment]
wa
i swear it could do paypal what the hell

guess im gonna change websites.... again

**Comment by X0nk** [comment]
okay i switched to kofi, i didnt know that site didnt support payal smh

i updated all the links on the github readme/modrinth/curseforge for that action

**Comment by Leclowndu93150** [comment]
time to fix this ?

**Comment by X0nk** [comment]
it is not something i can fix. go bug the tacz developer(s)

**Comment by Leclowndu93150** [comment]
mb i wasn't talking about you, i'm a mod developer myself, i want to fix it

**Comment by X0nk** [comment]
okay? well, unfortunately nothing in this thread can tell you what you need to do to fix it. i personally do not know what needs to be done, all i know is that it happens.
