### ISSUE TITLE
Shaders on iris 1.8.0 beta 4 are just... broken

### ISSUE THREAD

**Issue by Oxicodona** [X0nk/Bliss-Shader#309]
Hello, i'm writing here an issue related to iris shaders and gpu performance here too desperate to fix.

I play the pure version with sodium 0.6.0 beta 2 and iris 1.8.0 beta 4. When playing with shaders, the video card is not loaded above 20-30%, while it produces like 10 FPS and makes the game unplayable. Everything is fine on Optifine, the video card loads 80-100% and produces good FPS.

It is maybe an iris broken thing, because i have my drivers updated and minecraft is using my graphic card.

This is what happens if i turn on shaders on iris:

![image](https://github.com/user-attachments/assets/669e6135-bd6f-4229-b896-cff82b1b3339)

And the same shader but with optifine:

![image](https://github.com/user-attachments/assets/63a24e7c-9309-4bfb-b1e4-1526c36f14bc)

**Comment by X0nk** [comment]
i do not know why this happens, unfortunately. A shader cannot intentionally under-utilize the GPU/control utilization like that.
it would probably be better to ask iris or sodium support about it.
