### ISSUE TITLE
Chunkloading glitches out when used with the "Chunks Fade In" mod.

### ISSUE THREAD

**Issue by PlayfulPiano** [X0nk/Bliss-Shader#31]
Issue also occurs from the original V9 version, if that might help.
https://www.curseforge.com/minecraft/mc-mods/chunks-fade-in
https://github.com/kerudion/chunksfadein/issues/54

I've not had this type of issue from other shaders (complementary, seus), so it's definitely fixable. I'm just unsure what in V9 causes the problem.

**Comment by bemoty** [comment]
Here is a video showing the issue

https://github.com/X0nk/Bliss-Shader/assets/16725421/35c3df66-0d59-406d-b980-b1fdcddcbfbf

**Comment by X0nk** [comment]
this should happen on other deferred rendered shaders (photon, kappa, nostalgia, noble)
i do not know how to resolve such an issue
