### ISSUE TITLE
Distant images stacking up on my screeen

### ISSUE THREAD

**Issue by Harpyz02** [X0nk/Bliss-Shader#313]
### Describe the bug
Describe the bug in as much detail as possible. capturing footage of it with images or videos is preferred.

_Its a bit hard to describe it: whenever I move my camera, the distant images just seem to stick on the screen and create a glitchy effect_

### Describe how your minecraft is set up
1. Include a screenshot of the in-game f3 debug overlay. Please make sure it is fully visible.
![2024-10-13_17 04 41](https://github.com/user-attachments/assets/603120a1-9c9d-4923-8346-0291332c0d31)
I have the COMMIT #482 in-Dev version of Bliss

### Describe how to reproduce the bug
Show exactly how to make the bug appear, if you can. Video footage is preferred.

_Just putting the shader on will make the bug appear. Reloading shaders won't help._

https://github.com/user-attachments/assets/14e6e112-a3c2-4ce9-9b9c-8424a1529d28

Isolate the bug. some multiplayer servers cause issues on their own. in a newly made singleplayer world, with default/reset shader settings, show the steps to cause the bug

_I just downloaded the shaders from the Github. Playing in solo._

if it is happening on content from a mod, list what mod, and what content of that mod it happens on.

![image](https://github.com/user-attachments/assets/481852ef-8542-464f-afad-fcc3cf35a5e0)

if a specific shader setting can make it start/stop bugging, please list what shader setting does that.

**Comment by X0nk** [comment]
this is a super common issue, its not directly related to the shader itself, more of how iris and distant horizons interact.

you may be able to fix it by:
- ~~Disabling and re-enabling shaders (try this after each fix below)~~
- Ensuring Fabric API, Sodium, Iris, Indium, and Distant Horizons are all updated to their latest versions
- Setting Transparency to Complete in Distant Horizons config -> Advanced options -> Graphics -> Render Quality
- Resetting your Distant Horizons config by deleting DistantHorizons.toml from %appdata%/Roaming/.minecraft/config (restart your game for this to take effect)
- ~~Removing the "Methane" mod~~
- ~~Disabling Biome Ambient Light Coloring in Alex's Caves config~~
- Relaunching Minecraft
