### ISSUE TITLE
Cloud Settings not working with the newest version.

### ISSUE THREAD

**Issue by leonpa777** [X0nk/Bliss-Shader#314]
I am trying to change the density and coverage of clouds in the newest update, but nothing is changing. Height and Resolution is working fine tho.

![image](https://github.com/user-attachments/assets/f79280b3-5056-4881-8cb7-272064c16d71)

I am unsure if its caused by a mod or if it always happens.

**Comment by X0nk** [comment]
you have to turn daily weather off, as it overrides any custom settings
