### ISSUE TITLE
Sun flashbang

### ISSUE THREAD

**Issue by ToastyHawk** [X0nk/Bliss-Shader#317]
I'm using the latest in dev for Distant Horizons. I have many mods going but I've narrowed the issue down to one mod. Epic Knights: Shields, Armor and Weapons. The issue is the sun gets extremely bright and blows out everything when in third person or when swinging a weapon. It only does so when looking in certain direction, third person is pretty much 360 though. It doesn't matter if what I'm swinging is part of the mod or not. I'm also using better combat but I already ruled it out as the source of the issue. I've tried multiple versions of the mod but it made no difference. I thought it may be an issue with the auto exposure but after messing with those settings it didn't change anything. Any help or suggestion is appreciated.

https://medal.tv/games/minecraft/clips/iUj6JEwY7ATaQeTzA?invite=cr-MSx2cUosMjgzMTkzOTgyLA

Hopefully that video share works.

**Comment by X0nk** [comment]
hm... i have no clue how that even happens lol
i guess gotta start somewhere though.

could you test if disabling this setting does anything? 

`shader settings -> debug experimental -> TRANSLUCENT_ENTITIES`

this setting is proving problematic with alot of mods that change entity/player rendering.

**Comment by ToastyHawk** [comment]
Damn, that fixed it immediately lol. I'm impressed. Speedy reply too. Thanks man. Keep up the good work, Bliss is by far the most atmospheric shader I've used.

**Comment by X0nk** [comment]
glad the issue had a work around. 

unfortunately there was a cost; entities (not just mobs, block entities too) that are supposed to be see-through without shaders, are now completely opaque.

**Comment by ToastyHawk** [comment]
Seems like most stuff is still fine. Just glass seems to be messed up. Can still see through them but it bugs the water and the shaders get canceled through it. Definitely not ideal but it is what it is.

**Comment by ToastyHawk** [comment]
I was reading through some of the other closed tickets with issues similar to mine. Do you think the source of the issue is sodium when it comes to entities too? The translucent sorting issue that is.

**Comment by X0nk** [comment]
nah. sodium has added translucent sorting since sodium v0.6.0, so that version or newer wont have the problems related to sorting anymore

**Comment by ToastyHawk** [comment]
Yeah, I'm on 1.20.1 so I gotta wait for the backport of v0.6.0. Although now the shader is just like that with glass and stuff, even when turning the setting back on. Is fixing the translucent entity mod compatibility issue something you'll be looking to fix down the line?
