### ISSUE TITLE
Snow biomes at night have too much fog and are too bright

### ISSUE THREAD

**Issue by nonetrix** [X0nk/Bliss-Shader#319]
### Describe the bug
Night:
![image](https://github.com/user-attachments/assets/13ff5935-d898-4426-8208-19ff1da2639e)
Day:
![image](https://github.com/user-attachments/assets/6d5989ab-d716-458a-933c-5a7021341c1e)

https://github.com/user-attachments/assets/1ded857a-3a30-400c-8c09-2e8f57579d71

### Describe how your minecraft is set up
![image](https://github.com/user-attachments/assets/bb729996-b39d-4ab8-aeae-a714c48223e1)

### Describe how to reproduce the bug
1. Install https://modrinth.com/modpack/fabulously-optimized
2. Install Bliss
3. Go to snow biome
4. Set time to night

Able to reproduce with just Iris(1.7.3) and Sodium(0.5.11)

**Comment by nonetrix** [comment]
Unless this intentional, which for some reason I doubt, I don't think you get CS:GO flash banged irl if it turns night during winter... I could be wrong though, but I think this is a bug

**Comment by X0nk** [comment]
this is the same as [issue 162](https://github.com/X0nk/Bliss-Shader/issues/162)
