### ISSUE TITLE
Bug DOF (Latest github version)

### ISSUE THREAD

**Issue by ShrikerChestTree** [X0nk/Bliss-Shader#32]
Here's a screenshot of the bug itself:
![2023-10-23_20 26 34](https://github.com/X0nk/Bliss-Shader/assets/107254774/f19d4aab-a1c5-429c-ab57-824091f8ff24)
Iris 1.6.10
Sodium 0.5.3
Minecraft 1.20.2

**Comment by X0nk** [comment]
this is a known issue in the latest github commits. i was actually planning to get to fixing it today.

**Comment by X0nk** [comment]
i have fixed it in the latest commit, go grab that!

**Comment by ShrikerChestTree** [comment]
> i have fixed it in the latest commit, go grab that!

Good. Thanks!
