### ISSUE TITLE
Bliss not working with Distant Horizons, asks to use a different shaders

### ISSUE THREAD

**Issue by santacapra** [X0nk/Bliss-Shader#322]
Image below: The Distant Horizons error (Claims incompatibility with Bliss)
https://i.imgur.com/39SSqWE.png

F3 Overlay:
https://i.imgur.com/0oIKgK8.png

This happened upon opening a new world, Here's a screencap of my mods folder; the selected files are ones i recently added (and created a new world with them included).
https://i.imgur.com/Ep8KB3I.png

The error is most likely related to one of them i think, but it could've been one of the other mods

**Comment by X0nk** [comment]
distant horizons is correct in claiming it is incompatible. older bliss versions (specifically bliss v2.0.4 and older) do not have support for it.

you need the in-development version of bliss. [make sure to read the description/README of bliss's github page.](https://github.com/X0nk/Bliss-Shader) it tells you how to get the in-development version.
