### ISSUE TITLE
Buggy/flickering clouds

### ISSUE THREAD

**Issue by Skillkiller** [X0nk/Bliss-Shader#324]
### Describe the bug
The clouds look different than expected with the Distant Horizon mod. There is a kind of flickering in the clouds which creates a certain pattern.

![Video](https://github.com/user-attachments/assets/a73e57e4-9196-40ed-8c5f-8a51c2cad903)
![2024-10-27_04 23 09](https://github.com/user-attachments/assets/6303b6b4-c758-4e07-af6c-348c73a9fb93)

### Describe how to reproduce the bug
1. Create a world with heigh mountains. Example See 7644964991330705060
2. Fly very high
3. Show far in the distance

In the given fotage the Distant Horizon mod is used.

**Comment by Skillkiller** [comment]
Is there an option to completely deactivate the flickering clouds?

**Comment by Skillkiller** [comment]
Flickering without Distant Horizon Mod
https://github.com/user-attachments/assets/a5973c8f-ab2e-4d56-96f8-aa1d08a6fadd

**Comment by X0nk** [comment]
this is normal. the clouds are just terrible in terms of clarity. im working on a solution which will vastly improve it.
best you can do at the moment is increase the min/max raymarching steps in cloud settings, or increase resolution scale in fog settings
