### ISSUE TITLE
Rain and textures visual bugs with Conquest Reforged mod

### ISSUE THREAD

**Issue by Z0nbeKazel** [X0nk/Bliss-Shader#326]
When I install the Conquest Reforged mod blocks lose texture and turn grey when mining. Also when it rains there is a strange fog and a lot of blur.
Other mods are only embeddium and oculus.

![2024-10-28_18 52 53](https://github.com/user-attachments/assets/4a0d20fd-5c8b-4fd4-bb81-20f7e29df9a1)
![2024-10-28_19 00 32](https://github.com/user-attachments/assets/e5f71e3b-e014-45da-aeb3-4896a0af7ee0)
![2024-10-28_18 46 03](https://github.com/user-attachments/assets/fd43778f-a6fa-43b3-888c-516842a7c6e1)

**Comment by X0nk** [comment]
ive seen this before. conquest reforged doesnt allow the rain texture to reach zero alpha, so the bloomy rain effect thinks its a big raindrop. so essentially all the rain planes that the texture scrolls on become a massive raindrop in every direction.

the only things to do are
A: turn off bloomy fog `shader settings -> fog settings -> set bloomy fog to zero`
B: delete the raindrop texture out of the conquest reforged textures

**Comment by Z0nbeKazel** [comment]
Thaks, but how can i fix grey blocks?

**Comment by X0nk** [comment]
that the block breaking effect of conquest. i dont know what bliss version youre using as the GUI scale cut that off, but im assuming its v2.0.4. the in-development version reworked how the block breaking effect is blended, and works closer to vanilla now.
