### ISSUE TITLE
Feature request: Option to reduce or disable Nether and End fog

### ISSUE THREAD

**Issue by aleabodo** [X0nk/Bliss-Shader#33]
Right now it is very irritating to build things in the Nether and End, especially farms. The fog effect looks really nice but the moment you go into one of the haze veils you can't see anything at all. 

I suggest that once you actually go inside the for, that the fog close to the player is reduced or removed such that the player has better visibility to blocks in close proximity. Thus, I suggest that the fog effect (which looks really nice) should be primarily be rendered in the middleground to background.

Another option is that the shaderpack provides an option to reduce or disable the fog to their liking. I was not able to find any such option in the settings.

I provide a screenshot down below. In that screenshot I can barely see two chunks because of the fog veil I'm standing in. This is a picture of a Nether highway with view distance 12 chunks. I'm using a ressource pack, but I tried without with similar apparence.

![image](https://github.com/X0nk/Bliss-Shader/assets/25036049/7bd5bd6a-c0f3-46ea-bfd3-35ee4b056bd8)

**Comment by X0nk** [comment]
fog settings for both dimensions are already planned to be added, worry not.

**Comment by X0nk** [comment]
settings to control the density of both dimension fogs has been added.
