### ISSUE TITLE
Planar reflection

### ISSUE THREAD

**Issue by Fraws99** [X0nk/Bliss-Shader#335]
Could you add planar reflections to bliss water? SSR is fine, but it cut off reflections at the edge of the screen and this breaks the game immersion, especially when moving.

https://github.com/user-attachments/assets/42b83d9d-28d7-44ea-8214-7e8eaa5bdd91

**Comment by X0nk** [comment]
planar reflections are possible to do, but would not work well. they only work for a flat surface with a fixed position.
So the moment the water isnt flat, and isnt at a specific y level, it wont work good at all. would also be pretty terrible for performance as well.

**Comment by Fraws99** [comment]
Thank you for the quick reply, i understand it would just be a waste of time. Anyway thanks for this amazing shader
