### ISSUE TITLE
Particles not glowing with shader

### ISSUE THREAD

**Issue by MAXO1111111** [X0nk/Bliss-Shader#336]
im using bliss-shaders-main (or "Bliss In-Dev Version COMMIT #482 for Distant horizons and not sure if its possible or if there is a setting im missing but most particles don't seem to glow at all. I've looked for a good amount now in all the bliss settings i know its still in development but i was wondering if this will be added since i very much enjoy glowey particles. I know that many other shaders have this feature as well, and vanilla Minecraft has glowing particles. particles not glowing include all fire particles, enderman and dragon breath particles, end rod sparkle particles maybe more.

i was just wondering if its me or if it possibly could be added in the future or is in the works already.

**Comment by X0nk** [comment]
have you enabled "floodfill lighting"? because it would disallow some glowing things to work

**Comment by MAXO1111111** [comment]
sorry for responding late, it indeed was floodfill that was making the particles not glow. thank you very much! maybe for later versions put a note that some particles may not glow with it enabled so you don't keep getting this question in the future. thank you again!
