### ISSUE TITLE
Bliss render error

### ISSUE THREAD

**Issue by denny4-user** [X0nk/Bliss-Shader#337]
_Hello, I noticed this bug:_

Multiplayer:
![image](https://github.com/user-attachments/assets/4b581f84-f862-4c5d-b242-8f68b334f824)

Single player:
![image](https://github.com/user-attachments/assets/cccecbc6-d9cf-4fd2-a50f-026f66f0e773)

**Version:** `1.20.1`
**Fabric loader:** `0.16.9`

_Mod and shader settings are STANDARD._

**List of mods:**
- DistantHorizons-2.2.1-a-1.20.1-forge-fabric.jar
- fabric-api-0.92.2+1.20.1.jar
- indium-1.0.34+mc1.20.1.jar
- sodium-extra-0.5.4+mc1.20.1-build.115.jar
- sodium-fabric-0.5.11+mc1.20.1.jar
- iris-1.7.5+mc1.20.1.jar
- lazydfu-0.1.3.jar
- fabrishot-1.10.1.jar
- cwb-fabric-3.0.0+mc1.20.jar
- ferritecore-6.0.1-fabric.jar
- starlight-1.1.2+fabric.dbc156f.jar
- ImmediatelyFast-Fabric-1.3.1+1.20.4.jar
- modmenu-7.2.2.jar
- cloth-config-11.1.136-fabric.jar

**Comment by X0nk** [comment]
this isn't a bug. there simply is not a shadow rendered from that far away. you will need to enable the DH shadowmap: `shader settings -> supported mods -> distant horizons`

**Comment by denny4-user** [comment]
![2024-11-07_00 06 10](https://github.com/user-attachments/assets/ac19a592-f53d-4df2-895f-ce3d47747337)
💀

**Comment by denny4-user** [comment]
how fix this...

**Comment by denny4-user** [comment]
Please

**Comment by X0nk** [comment]
oop i forgot about that lol
yeah thats a recent issue in iris pretty sure, when enabling the DH shadowmap, the normal shadowmap kinda explodes and dies.
i dont know if i can fix it. i most likely will have to wait for iris to fix it

**Comment by denny4-user** [comment]
OK, I'll be waiting, thanks for the feedback :)
