### ISSUE TITLE
Texture pack used in screenshot

### ISSUE THREAD

**Issue by taedium8vitae** [X0nk/Bliss-Shader#338]
Hey!
I've been trying to find which texture pack was used in the screenshot used in the readme but even with close to an hour of scrolling i've come nowhere close. Does anybody know which one it is? I find it really beautiful.
Thanks in advance

**Comment by X0nk** [comment]
i swear i put credits there lol
it is pixel perfection [heres a link](https://www.planetminecraft.com/texture-pack/pixel-perfection-chorus-edit/)

**Comment by taedium8vitae** [comment]
Thanks a lot! Also the shaders are impeccable 🥰
