### ISSUE TITLE
INCORRECT UNDERWATER SHADOWS RENDERING

### ISSUE THREAD

**Issue by Fraws99** [X0nk/Bliss-Shader#339]
**Shader Bliss-shader-main commit #482**
Underwater shadows aren't rendered correctly below a certain y level, seems to be the level 51.0
![2024-11-11_13 33 23](https://github.com/user-attachments/assets/592b3665-a5f8-446d-9668-5f7805888223)

Shadows above y 51.0
![2024-11-11_13 05 23](https://github.com/user-attachments/assets/5ac48cee-1aad-43e9-9a33-25465af76e2a)

Shadows below y 51.0
![2024-11-11_13 05 59](https://github.com/user-attachments/assets/7ac6628b-9760-46a3-88cd-88af5c699197)

https://github.com/user-attachments/assets/bd3575e3-29ae-4aaf-93dc-de19b31e3058

In-game f3 debug overlay
![2024-11-11_13 28 41](https://github.com/user-attachments/assets/023aa17f-a6fb-4cdc-a5a6-0a3372040db5)
****
From what i've tested, it seems there's no specific shader setting that can make it start/stop bugging.
I'm currently using the latest version of Distant Horizon mod for Fabric 1.21, but the bug is still present without DH.

**Comment by X0nk** [comment]
this is the lightleak prevention kicking in, i forgot to make it not work under water lol.
i have to zoom the shadowmap up and center it to a block, so the gaps that leak get mostly filled up by shadow. its hacky but better than removing shadows completely
