### ISSUE TITLE
Can't see in the nether

### ISSUE THREAD

**Issue by LizTheMenace** [X0nk/Bliss-Shader#35]
Whenever i'm in a basalt or soul biome, i can't see more than a few blocks in front of me
![2023-11-19_16 08 09](https://github.com/X0nk/Bliss-Shader/assets/150865997/1e0e98a0-51ae-4e7f-adbb-5b27d00f2af4)

**Comment by X0nk** [comment]
that's just fog. there is no way to adjust the nether fog yet.
settings to adjust fog in other dimensions are planned to be added, so stay tuned.
