### ISSUE TITLE
NOISY TEXTURE IN DH TERRAIN

### ISSUE THREAD

**Issue by Fraws99** [X0nk/Bliss-Shader#352]
I'm using the latest in-developement version of Bliss shader with DH mod enabled.
Is it possible to add noisy texture in Distant Horizon terrain? Textures look a bit flat in the distance

![2024-11-25_17 34 47](https://github.com/user-attachments/assets/0b16541c-2181-4036-bf1d-1e35b85fb2ba)
![2024-11-25_17 39 42](https://github.com/user-attachments/assets/5bb453a2-e52b-47c3-ab40-59f83c058fec)

Here're some examples for a better explanation:

- The DH default noisy texture without any shaders

![2024-11-25_17 34 00](https://github.com/user-attachments/assets/d55697d9-0d57-4bc5-9bba-2f66682d9a9f)
![2024-11-25_17 39 25](https://github.com/user-attachments/assets/1d8b7a60-8b41-4c0f-944e-34a93f234558)

- The noisy texture from Photon shader

![2024-11-25_17 34 27](https://github.com/user-attachments/assets/5d441338-9899-426e-b80f-d0b55267e471)
![2024-11-25_17 39 12](https://github.com/user-attachments/assets/01291979-5752-48c0-989a-6387248adcbb)

**Comment by X0nk** [comment]
i have already added this in the unstable development branch. it should be coming to the main branch soon

**Comment by Fraws99** [comment]
Oh cool, thanks
