### ISSUE TITLE
1.21.1 support?

### ISSUE THREAD

**Issue by TheeMrCheeky** [X0nk/Bliss-Shader#355]
blah blah blah blah
shocked this isn't downloadable on 1.21.1 since its the most preferred for mods

**Comment by Merlin1809** [comment]
What are you talking about? It works fine on 1.21.1.

**Comment by X0nk** [comment]
yeah it works fine on 1.21.1

shaders do not care about Minecraft versions, outside of how block IDs change. shaders only need a shader loader mod with all the features it uses.
