### ISSUE TITLE
Vision whites out at start and end of each day

### ISSUE THREAD

**Issue by retropele** [X0nk/Bliss-Shader#36]
Hi, I'm sorry to report this here but I've got no idea how else to fix it.

First off THANK YOU :heart: for this amazing shader, I love the variable weather and the gorgeous effects. Even though I have a machine that suffers for it I always run this shader, it makes everything look so lovely and alive.

I can't figure out what setting might be causing this, but my game gradually whites out (like it's supposed to be a sort of bright, godray-ish effect), but my entire game's vision except for like 6 blocks in front of me turns completely white.

It makes the game really unplayable for me bc I'm a bit light sensitive, but I also can't see or do anything in the game beyond that time.

Do you have any idea what could be causing this? I'll add screenshots for completeness: there are some as the bloom-out intensifies, what it makes everything look like, and some shots of what it normally looks like (on a foggy day in your mod).

If you have any idea what might be causing it I'd be happy to toggle that option if possible, if it's just on my end, but none of the options I've messed with seem to have resolved it.

Thank you so much.

Normal shader function:

![2023-11-30_04 12 10](https://github.com/X0nk/Bliss-Shader/assets/123419913/67e796ef-604a-4299-a920-babde8230852)
![2023-11-30_04 12 09](https://github.com/X0nk/Bliss-Shader/assets/123419913/d682d1ca-bd97-46b7-a8ef-b99962720d7f)

White out starts and gets worse:

![2023-11-30_04 10 09](https://github.com/X0nk/Bliss-Shader/assets/123419913/eeccc808-8b45-4802-b896-a44ec7ca6839)
![2023-11-30_04 10 11](https://github.com/X0nk/Bliss-Shader/assets/123419913/f490b653-e20a-4c7f-8883-f90518fd3e26)
![2023-11-30_04 10 12](https://github.com/X0nk/Bliss-Shader/assets/123419913/5c98c4b6-dde9-4a09-8896-a853bd9b1928)

Environment when whited-out:

![2023-11-30_04 10 16](https://github.com/X0nk/Bliss-Shader/assets/123419913/fb22f7a6-86c7-453e-b7bf-f031a0513dde)
![2023-11-30_04 10 17](https://github.com/X0nk/Bliss-Shader/assets/123419913/9fb64bd1-4791-4493-905a-50a0c9035685)

**Comment by X0nk** [comment]
thanks for the bug report! glad you enjoy the shader so far.

i have a few questions

what version of the shader are you using?

does this happen at default settings?

does this happen without any additional mods besides the one that loads the shaders?

**Comment by retropele** [comment]
Thank you for getting back to me so quickly!

I am using version 2.0.4 of the mod.

I reset to default settings, I am just using sodium and iris (to enable the shader) but that's it - it is still whiting out. Here's a screenshot of what it looks like with these settings:

![2023-11-30_05 15 23](https://github.com/X0nk/Bliss-Shader/assets/123419913/3ec6d6f2-9a85-469d-92e2-ae9a6d61c502)
![2023-11-30_05 14 57](https://github.com/X0nk/Bliss-Shader/assets/123419913/0c6cd261-3183-409d-9170-0c186eb8edb9)
![2023-11-30_05 14 51](https://github.com/X0nk/Bliss-Shader/assets/123419913/d73a432d-b6ae-4f93-8524-60c64dc19098)

**Comment by X0nk** [comment]
does this still happen on the latest github commit (aka in-development versions)?

to get these, go to the main area of the bliss github with the description and everything, click the big green code button, and download as zip.

**Comment by retropele** [comment]
I downloaded the dev version and the sunrises and sunsets seem to be completely fixed!

That and the game looks really radiant, even better than before.

Thank you very much for helping me troubleshoot this! :)
![2023-11-30_07 00 20](https://github.com/X0nk/Bliss-Shader/assets/123419913/6ba8c583-23a3-4755-a94c-5d5f6979326f)

**Comment by cpof-tea** [comment]
I encountered this issue too, but on Forge build with: Embeddium (Sodium fork) + Oculus (Iris fork) + FFAPI + Sinytra Connector with Bliss v2.0.4

> go to the main area of the bliss github with the description and everything, click the big green code button, and download as zip

Also helped. Thank you!
