### ISSUE TITLE
Translucent Armor

### ISSUE THREAD

**Issue by TheEpicChunk** [X0nk/Bliss-Shader#362]
For some reason my armor is translucent when I wear it. This isn't isolated to just netherite armor, in fact iron armor kind of makes me look like a ghost, but netherite is just the armor I chose to use for the example.
![2024-12-03_17 51 04](https://github.com/user-attachments/assets/ac188127-20c0-4626-89e6-577aab32033a)

![2024-12-03_17 53 24](https://github.com/user-attachments/assets/048f266f-43d0-4b38-8d97-b7cb41a2316c)

I know I don't have to do this if I give the f3 screenshot but I will anyways
I use NVIDIA
I use Windows
I'm running Minecraft 1.21.3
No client, just fabric
I'm using Iris
I'm using Bliss-Shader-physics_ocean
I'm using AutoHUD, CameraOverhaul, C2ME, Continuity, DH, DynamicFPS, DynamicLights, EMF, ETF, EntityCulling, FerriteCore, FirstPerson, ImmediatelyFast, Iris, Lithium, MoreCulling, Noisium, NotEnoughAnimations, PhysicsModPro, ShoulderSurfingReloaded, Sodium, and WI Zoom.

Just turn on the shader, no extra settings or anything.

In a singleplayer server, again no extra settings.

**Comment by X0nk** [comment]
this is a conflict between shoulder surfing and iris.

there are 2 workarounds:
A: change the shoulder surfing mod config parameter `adjust_player_transparency` to false. if you have mod menu its called player translucent or something (i dont use it so im going off memory lol)
B: turn off TRANSLUCENT_ENTITIES in shader settings -> debug/experimental
