### ISSUE TITLE
Cave fog causing sky to go black?

### ISSUE THREAD

**Issue by Jenexs** [X0nk/Bliss-Shader#363]
### Describe the bug
Sky goes black when roof over head, or in what game considers "cave"
### Describe how your minecraft is set up
![2024-12-07_01 18 47](https://github.com/user-attachments/assets/f4fad2ff-250d-4598-b67e-41b309f039ea)
![2024-12-07_01 19 15](https://github.com/user-attachments/assets/69bded1a-79d3-4f31-b6da-8fdc367ee27c)

### Describe how to reproduce the bug
Go in any hole in the wall of a mountain or house roof and have CAVE FOG enabled. Seems to be related with how the cave fog is determined.

**Comment by X0nk** [comment]
this is intended. i blot out the sky so if a chunk is unloaded whilst inside a cave, the bright sky does not create a giant shining bright spot.

but unfortunately, accurately detecting when you're actually in a cave is very difficult, and there is no good way to do it. iris/optifine do not give much information about the world, and i cant "just get it" either.
the cave fog uses a basic test, it just waits for about 10 seconds if you're in a sky light level of zero before activating, and deactivates when you go to a higher light level... sadly light level zero exists in houses, under floating islands, large cliff overhangs, ect. so it doesnt exactly only happen in caves only.

**Comment by Jenexs** [comment]
Fair enough. Excuse my ignorance, but with enough torches is it possible to get it away from light level 0? On Dec 10, 2024 5:48 p.m., Xonk ***@***.***> wrote:
this is intended. i blot out the sky so if a chunk is unloaded whilst inside a cave, the bright sky does not create a giant shining bright spot.
but unfortunately, accurately detecting when you're actually in a cave is very difficult, and there is no good way to do it. iris/optifine do not give much information about the world, and i cant "just get it" either.
the cave fog uses a basic test, it just waits for about 10 seconds if you're in a sky light level of zero before activating, and deactivates when you go to a higher light level... sadly light level zero exists in houses, under floating islands, large cliff overhangs, ect. so it doesnt exactly only happen in caves only.
