### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by FLEXORPRO** [X0nk/Bliss-Shader#37]
Bugs: Mod
Physical mod pro 164 fabric 1.20.2
When I run out from under my feet, it's not particles with block textures, but some crap made of a lot of textures.
Request:
Please add a light adjustment of the darkness of the night by type:
Dark night; Standard; Bright night; Very bright night; Very dark night.
Thank you in advance!!! Top-end and high-end shaders!!!
![2023-12-04_22 35 52](https://github.com/X0nk/Bliss-Shader/assets/152922552/815aeb0f-ed3a-4a95-9c7c-3eb22cb93838)
![2023-12-04_22 35 52_2](https://github.com/X0nk/Bliss-Shader/assets/152922552/0261434d-dfdc-4c88-8c72-5494cb3df532)
![2023-12-04_22 35 52_3](https://github.com/X0nk/Bliss-Shader/assets/152922552/b8be28ab-222e-4994-ae9a-84b04b1e98c7)
![2023-12-04_22 35 53](https://github.com/X0nk/Bliss-Shader/assets/152922552/9679dfda-2186-4e83-b7ad-2dfd0ccfdd08)

**Comment by X0nk** [comment]
i am going to be honest, i very much do not want to even bother trying to support physics mod anymore... it does a handful of weird stuff, i have to do like a bunch of special cases just for it, and some stuff (like smoke) i am not able to even get working correctly. it is a pain.

anyways, if you want to increase the brightness of night time, simply boost the moonlight illuminance in `shader settings -> direct light`. i'm not sure if i added the moon-phase based brightness on/off toggle yet...
