### ISSUE TITLE
Shadow Filtering

### ISSUE THREAD

**Issue by Niryn** [X0nk/Bliss-Shader#374]
The bliss shaders (distant horzions support and non distant horzion support) has this thing when shadow filtering is on the snow looks like this at sunset when going close to snow and I was wondering if there is a way to keep shadow filtering on while not have snow glow up like this. version 1.21 
![2024-12-24_11 19 33](https://github.com/user-attachments/assets/9ce63e08-4d58-4524-81b1-3ef78eec9a46)

**Comment by Niryn** [comment]
I disabled SSS and it's gone but i like the look of SSS has on the environment so if in the config i can do something please let me know

**Comment by X0nk** [comment]
this isnt a bug, but an unfortunate result of subsurface scattering working properly.

the shadowmap is looking towards the player from underneath the mountain there, form the *unloaded* chunks part, theres no surface back there blocking the sunlight to cast a shadow.

i made a small illustration to try and explain it better... the green line represents loaded surfaces, a loaded surface is required for a shadow to be made.
the behind side of that mountain has no loaded surface, so no shadow is made. so the sunlight can go right up to the snow and scatter through it like normal.
![image](https://github.com/user-attachments/assets/a49512ef-fa32-4f43-910b-1f7230d5f5e3)
