### ISSUE TITLE
Bliss Shader Incompatible with the Aether Mod

### ISSUE THREAD

**Issue by KJFox12** [X0nk/Bliss-Shader#377]
### Describe the bug
When using the Bliss Shader with the Aether Dimension mod, it disables the shader in the dimension entirely.

### Describe how your minecraft is set up

Both normal and BetterF3 information:

![image](https://github.com/user-attachments/assets/5887b820-52d9-469f-b654-376d3c3a1a5a)

![Screenshot 2024-12-27 120435](https://github.com/user-attachments/assets/3a9b6b45-722d-4321-aaab-a6d512372ef1)

Mods Used:

BetterF3
Distant Horizons
Sodium/Embeddium Dynamic Lights
Sodium/Embeddium Options API
The Aether

Cloth Config API (Fabric/Forge/NeoForge)
Embeddium
Oculus

### Describe how to reproduce the bug

Just entering the dimension with the shader enabled causes the bug. Distant horizons is also being used.

Bliss Shaders Disabled:
![image](https://github.com/user-attachments/assets/e531d187-2a2d-4fc4-adf0-b15007c519d0)

Bliss Shaders Enabled:
![image](https://github.com/user-attachments/assets/5aad580a-3090-4d51-ab26-fb0675f4f087)

**Comment by KJFox12** [comment]
Is there a workaround to this? Or is this just something that needs to be fixed in an update?

**Comment by X0nk** [comment]
this is intentional, but can be easily changed, and is planned to be reverted.
read here for a guide: [issue 275](https://github.com/X0nk/Bliss-Shader/issues/275)
