### ISSUE TITLE
wonky nether camera when using shader

### ISSUE THREAD

**Issue by NightbladeGames** [X0nk/Bliss-Shader#38]
![2024-01-03_23 07 12](https://github.com/X0nk/Bliss-Shader/assets/155604384/4b21fe4e-270c-403c-b963-9603eec2fee4)
Whenever I enter the nether it loads like this idk what to do

**Comment by X0nk** [comment]
what version are you using?

**Comment by NightbladeGames** [comment]
2.0.4

**Comment by X0nk** [comment]
could you try the latest github commit? (big green "code" button, then download as zip)

ive changed alot since v2.0.4 and it may have been fixed

**Comment by NightbladeGames** [comment]
seemed to fix the issue. wacky bug tho amirite? surprised that i was the first to bring it up.

Thanks for the help.
