### ISSUE TITLE
Glass casts solid shadows on Iris (old bug from Chocapic)

### ISSUE THREAD

**Issue by MangoDev1** [X0nk/Bliss-Shader#4]
Another old bug from Chocapic. Regular glass (stained glass and tinted glass too, but plain glass doing it too is the weirdest) casts a solid shadow from sunlight. Nothing changes if `GLASS_TINT` is on or off.

All glass blocks cast solid shadows:
![2023-06-28_21 47 55](https://github.com/X0nk/Bliss-Shader/assets/94928669/a327a2ff-82c8-4fab-b3e9-4613f39c0812)

Minecraft versions tested: 1.20, 1.19.2, 1.18.2, 1.16.5
Mods: Sodium, Iris

This bug did not happen with regular Chocapic on Optifine, only on Iris does it do it.

**Comment by X0nk** [comment]
I do not know how or why iris cannot do stochastic transparent shadows, i will have to investigate that.
the Glass_tint setting simply makes the glass color tint the background more. it wouldn't change anything for shadows. it is poorly named.

**Comment by X0nk** [comment]
i might add them in the future whenever i get around to learning how shadowmaps work and getting my matrix math skills better
