### ISSUE TITLE
Temporal upscaling breaks nether portal frame rendering in the nether

### ISSUE THREAD

**Issue by antieksi** [X0nk/Bliss-Shader#45]
Rendering of nether portal frames with temporal upscaling is weird.

Using Iris.

![изображение](https://github.com/X0nk/Bliss-Shader/assets/95758843/52d069ee-d622-4631-9961-dfd49d10b61f)

**Comment by antieksi** [comment]
Oh, looks like it applies to all translucent blocks. 

Shader on:
![изображение](https://github.com/X0nk/Bliss-Shader/assets/95758843/f13aa32b-a1f1-4fa0-9056-65f06917990b)

Shader off:
![изображение](https://github.com/X0nk/Bliss-Shader/assets/95758843/895744ef-62fc-47f2-9c76-12ba74da6a45)

**Comment by X0nk** [comment]
these issues are currently fixed in the latest in-development version.
