### ISSUE TITLE
Beacon beams render on top of held items and entities

### ISSUE THREAD

**Issue by antieksi** [X0nk/Bliss-Shader#46]
If there is something in front of a beacon beam that is not a block, then it is rendered behind the beam.

Using Iris Shaders

![изображение](https://github.com/X0nk/Bliss-Shader/assets/95758843/3b5c28a9-c750-4086-a67b-47ff38621cb7)

![2024-02-24_13 43 26](https://github.com/X0nk/Bliss-Shader/assets/95758843/462b23e4-bb78-498e-a467-b8b0c2f0e1b3)

**Comment by X0nk** [comment]
what bliss version are you using?
