### ISSUE TITLE
Underwater view outside the glass wall looks buggy

### ISSUE THREAD

**Issue by ddodd123** [X0nk/Bliss-Shader#47]
![2024-02-25_15 06 28](https://github.com/X0nk/Bliss-Shader/assets/161188957/75622698-c1e4-4d9e-86a0-bc893ae0a5d3)
![2024-02-25_15 06 36](https://github.com/X0nk/Bliss-Shader/assets/161188957/bbc67eab-87d9-4ed3-8e91-ae5d13d111d7)

Although this seems to also happen with the original Chocapic13 shader, is it possible to fix it?

Also 2 suggestions:
1. I think it would be better if the sky color was a bit more vibrant. A little bluer during the day and more reddish at sunset.
2. I wish the water was more visible. I can barely see the water in a 1 block deep puddle or stream in a cave because it's too transparent. I did try adjusting the dirt value, but that makes it hard to see when swimming in the water.

Thank you for all your hard work.

**Comment by X0nk** [comment]
probably related to sodium not having translucent sorting in release versions yet

**Comment by X0nk** [comment]
sodium is finally going to have translucent sorting in their next release version so.. this isnt really a bliss issue in the first place
