### ISSUE TITLE
Underground nether missing any sort of shadows.

### ISSUE THREAD

**Issue by Sheepss** [X0nk/Bliss-Shader#5]
Is this intended? It seems being underground in the nether removes fog and everything is perfectly lit up.

Fog exists on the "surface" of the nether. 

1.19.2 Fabric using iris 1.6.0

![image](https://github.com/X0nk/Bliss-Shader/assets/29313321/585476e5-d93c-4337-bd6d-f3e48a45da11)

![image](https://github.com/X0nk/Bliss-Shader/assets/29313321/1ba856e6-192e-48c8-af2b-76400e6502ec)

**Comment by X0nk** [comment]
The nether doesn't have shadows on any shader other than ones that do lighting with voxels like seus ptgi or rethinking voxels.
however, Bliss's nether takes the fog color into account for some lighting, and better nether has _reeaally_ bright fog colors, so it skewed the balance i had in vanilla nether while making the shader lol. i might try to balance it out for better nether and vanilla to look alright in both cases.

my nether shader is a stand-in at the moment until i get some ideas on what to do with it anyway.
