### ISSUE TITLE
Slime Mobs are missing their transparency layer.

### ISSUE THREAD

**Issue by aarontt20** [X0nk/Bliss-Shader#50]
I think slimes might be one of the only mobs that have a translucent effect on them, making it so you can actually see a bit though them. I have noticed that with Chocapic13/Bliss shaders, the transparency layer on these mobs are lost entirely and they just look like a green cube:
![2024-03-02_19 47 23](https://github.com/X0nk/Bliss-Shader/assets/5964761/843dad92-214a-4718-9a88-4882c005aa4c)

If you compare this to base Minecraft, or even other shaders such as BSL, the transparency effect still stands and you can see through the slime no problem:
![2024-03-02_19 47 35](https://github.com/X0nk/Bliss-Shader/assets/5964761/bb9e907f-285f-47ef-a660-d45ea5354437)

It would be really nice if we could restore this effect on slimes to make them partially see through again, even just to see their faces.

**Comment by X0nk** [comment]
this is a trade-off with how bliss/chocapic is designed.
as they are hybrid deferred-forward rendering, translucent stuff is handled in a specific way...
translucent things are shaded separately from opaque things, and have a very basic shader. opaque things get the more complicated shading. now entities/mobs, i have to choose... make them use the translucent layer, and have basic lighting, and break with water fog blending, or have complicated shading and blend in correctly, but slimes are solid.

i say it was a fair sacrifice.

however, that is not the issue if youre using iris shadersmod. it allows me to single out translucent entities and opaque entities, and shade them according to their render type, so slime get shaded correctly. optifine does not have this feature.
