### ISSUE TITLE
Change sunrise/sunset times

### ISSUE THREAD

**Issue by Macintosh-Fan** [X0nk/Bliss-Shader#55]
No idea if it is possible, even with editing the shader pack directly, but I am wondering if there is a way to have the sunrise/sunset time change, depending on the time of year, or even just setting the sun angle, but being able to shift it up/down. Something like [this](https://www.timeanddate.com/sun/@49,0), at 49°N 0°E.

**Comment by Macintosh-Fan** [comment]
Also, since the shaders have seasons, maybe another feature with this could be to have the sun angle change accordingly (and an option feature to change the **apparent** sunset/sunrise times for the client)?

**Comment by X0nk** [comment]
sorry i never replied to this... i kinda forgot.

changing the position of the sun is difficult if i want it to still be in sync with Minecraft time.
the shadows from the sun use some matrices that i would have to custom remake to give it a custom position, as iris/optifine do not give the ability to customize it. i already attempted this before for another reason, and ran into some roadblocks. i may revisit it again.

also, the sun angle is a constant variable, which means it cannot change unless the entire shader reloads.

**Comment by Macintosh-Fan** [comment]
Maybe a feature request to make for Iris on the developer-side-of-things?

**Comment by X0nk** [comment]
i have already talked about it with IMS (developer of iris) in passing, i can bring it up directly again some other time, but such a thing is very low priority at the moment.

**Comment by X0nk** [comment]
incase you wondered, the reason i wanted custom matrices for the shadowmap was so i could make the moon have a detached orbit from the sun, but still have a working shadowmap. this would be cool in a few ways... the moon would be visible during the day, i could do eclipses, and it opens up the potential to do neat stuff in the end/nether if i wanted.

**Comment by Macintosh-Fan** [comment]
No longer possible?

**Comment by X0nk** [comment]
being possible/impossible is not the reason i closed this.
custom sun/moon position is simply an idea, and as i said before, very low priority if i ever do decide to make it
