### ISSUE TITLE
Hurt effect on players does not work.

### ISSUE THREAD

**Issue by Pizztakio** [X0nk/Bliss-Shader#57]
The red overlay on the player entity when the player takes damage is not working.

demonstration

https://github.com/X0nk/Bliss-Shader/assets/105042017/90eca5ab-b9bc-4c56-98ce-249eb1a0d49c

**Comment by X0nk** [comment]
this is just a small oversight on my part. i started using iris's translucent entities programs, and simply forgot to implement the color flash
