### ISSUE TITLE
Particles bug

### ISSUE THREAD

**Issue by TimeShadowStudios** [X0nk/Bliss-Shader#61]
Hello, 

we are using the v1.15 version of the Bliss Shader, because unfortunately only this version works for our Minecraft version.

Particles are displayed in a strange colour and bug around when there is a block behind them. (See picture)
Maybe a UV problem?
Does anyone have any idea how to fix this?
![Uploading image.png…]()

**Comment by TimeShadowStudios** [comment]
![image](https://github.com/X0nk/Bliss-Shader/assets/89359238/18a7c1fa-35c4-4517-9b04-e97b278b0373)

**Comment by X0nk** [comment]
> we are using the v1.15 version of the Bliss Shader
sorry that version is like 2 years old, i am not providing support for it. you're on your own.
