### ISSUE TITLE
floating chest where player was when loading shaders

### ISSUE THREAD

**Issue by lioni-a** [X0nk/Bliss-Shader#62]
im using this mod pack https://www.curseforge.com/minecraft/modpacks/prominence-2-rpg
idk why this happens its just odd 
![image](https://github.com/X0nk/Bliss-Shader/assets/162006280/8a204020-230c-43b4-af33-419e131a7c2c)

**Comment by X0nk** [comment]
Does this still happen when there are no shaders enabled?

**Comment by lioni-a** [comment]
> Does this still happen when there are no shaders enabled?

no it only happens with this shaders not others

**Comment by X0nk** [comment]
does it happen on the latest in-development version? (this will download the shader when you click it) https://github.com/X0nk/Bliss-Shader/archive/refs/heads/main.zip

**Comment by lioni-a** [comment]
> does it happen on the latest in-development version? (this will download the shader when you click it) https://github.com/X0nk/Bliss-Shader/archive/refs/heads/main.zip

no it dosnt odd
