### ISSUE TITLE
Shaders do not load on Iris 1.7 on MacOS Sonoma 14.3

### ISSUE THREAD

**Issue by AnselmeMas** [X0nk/Bliss-Shader#64]
Machine :
MacBook Pro M1Pro 10/16cores 32GB RAM
MacOS Sonoma 14.3

Version :
Prism launcher 8.2
Minecraft 1.20.4
Fabric 0.15.7

Mods :
(DistantHorizons-fabric-2.0.2-a-dev-1.20.4.jar) - Unrelated to DH as the issue persists when deactivating the mod
fabric-api-0.91.1+1.20.3.jar
indium-1.0.30+mc1.20.4.jar
iris-1.7.0-snapshot+mc1.20.4-5983468.jar
sodium-fabric-0.5.8+mc1.20.4.jar

Error log:

composite2: composite2: WARNING: Could not find vertex shader attribute 'at_tangent' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'mc_midTexCoord' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'UV0' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'iris_Entity' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'at_midBlock' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'mc_Entity' to match BindAttributeLocation request.
WARNING: Output of vertex shader 'iris_FogFragCoord' not read by fragment shader
WARNING: Output of vertex shader 'zMults' not read by fragment shader
ERROR: Implementation limit of 16 active fragment shader samplers (e.g., maximum number of supported image units) exceeded, fragment shader uses 17 samplers

**Comment by X0nk** [comment]
known issue. you're out of luck.
you'll just have to wait for me to efficiently handle my texture read/writing

**Comment by AnselmeMas** [comment]
Gotcha no worries we had already warned me in the discord. Wasn't sure if it was documented yet si I figured I'll just get you as many details as possible here. Good luck and thanks for your work!

**Comment by Spectralo** [comment]
Same problem on a M1 Max Macbook pro ...

composite2: composite2: WARNING: Could not find vertex shader attribute 'at_tangent' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'mc_midTexCoord' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'UV0' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'iris_Entity' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'at_midBlock' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'mc_Entity' to match BindAttributeLocation request.
WARNING: Output of vertex shader 'iris_FogFragCoord' not read by fragment shader
WARNING: Output of vertex shader 'zMults' not read by fragment shader
ERROR: Implementation limit of 16 active fragment shader samplers (e.g., maximum number of supported image units) exceeded, fragment shader uses 19 samplers

Sad :/ I wanted to use it with Distant Horizons

**Comment by davidishkaa** [comment]
Same on M3 Max just trying to use it with DH 😭 

composite2: composite2: WARNING: Could not find vertex shader attribute 'at_tangent' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'mc_midTexCoord' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'UV0' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'iris_Entity' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'at_midBlock' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'mc_Entity' to match BindAttributeLocation request.
WARNING: Output of vertex shader 'zMults' not read by fragment shader
WARNING: Output of vertex shader 'iris_FogFragCoord' not read by fragment shader
ERROR: Implementation limit of 16 active fragment shader samplers (e.g., maximum number of supported image units) exceeded, fragment shader uses 17 samplers

**Comment by X0nk** [comment]
read this issue [here](https://github.com/X0nk/Bliss-Shader/issues/181)
