### ISSUE TITLE
Bloom missing for candles

### ISSUE THREAD

**Issue by churchner420** [X0nk/Bliss-Shader#7]
There is no bloom for candles and the light from candles is minimal

**Comment by X0nk** [comment]
if forgot to add candles to the list of lightsources to do the normal stuff on it... i got it fixed now though, go grab the latest.

but yea, bloom is not picky. it just needs something on the screen to be bright to work.

i cannot control how much light comes from candles either, i can only control the gradient of the lightmap, across the entire world.
