### ISSUE TITLE
Lighting turning off when looking in angles, weird grids, sky not clearing each frame resulting in stacking/burn in

### ISSUE THREAD

**Issue by goober0013** [X0nk/Bliss-Shader#71]
I can't find any other people having this glitch (dev's worst nightmare I'm sure) but for some reason I'm having several graphical glitches that are best explained in these screenshots.
![image](https://github.com/X0nk/Bliss-Shader/assets/160344941/0db014ba-8c4a-41a1-aa5b-edc697e5b324)
![image](https://github.com/X0nk/Bliss-Shader/assets/160344941/82baa48f-c1d1-464f-a493-164138aa6e7f)
![image](https://github.com/X0nk/Bliss-Shader/assets/160344941/b2ff2317-d9da-4de4-8751-68054075aa4a)

The sky thing is hard to explain in the screenshot, but basically when I turn to look in a different direction then the sky doesn't remove last frame's details resulting in a permanent mark on the screen until I look at ground again.

Screenshots of me not using the shader:
![image](https://github.com/X0nk/Bliss-Shader/assets/160344941/389caed8-47a2-440c-a850-a7cfdbded351)
![image](https://github.com/X0nk/Bliss-Shader/assets/160344941/149a017a-9cc8-4559-b60c-9b2c3306dab1)
![image](https://github.com/X0nk/Bliss-Shader/assets/160344941/c7c15410-8c87-4ff8-aa0e-6311a37bb0d3)

I have tried with and without the FabricSkyboxes mod thinking this would force SOMETHING to render... didn't work

Also the night is not dark at all
![image](https://github.com/X0nk/Bliss-Shader/assets/160344941/b3485206-596b-4935-8238-03cb9e62ebab)
![image](https://github.com/X0nk/Bliss-Shader/assets/160344941/684d7b5a-b5cc-4e39-9d71-b894619a49a2)

With night vision:
![image](https://github.com/X0nk/Bliss-Shader/assets/160344941/4e706f2a-73c0-44a2-a731-1dc5f518a6e4)

In all these photos the LODs seem incredibly dark
I could try brightness options, but I've seen this shader correctly light the LOD chunks, and it even appears somewhat successful at certain angles.

**Comment by X0nk** [comment]
this is a known issue, it's just distant horizons dying. normally you just restart the game, but others have said that fixes nothing.

supposedly this fixes it:

"To fix the image glitch issue, you need to go to DH - advanced options > graphics > rendering > change transparency to complete"

**Comment by goober0013** [comment]
That is actually the dumbest most genius solution, what the hell? Thanks for the fix!
![image](https://github.com/X0nk/Bliss-Shader/assets/160344941/7088139c-dd8f-4906-a3da-2318608ce588)
