### ISSUE TITLE
White Breaking Texture Bug

### ISSUE THREAD

**Issue by RandomKall** [X0nk/Bliss-Shader#76]
I have this White breaking texture for all blocks ive looked everywhere cant find a fix 
![unknown_2024 03 18-19 56](https://github.com/X0nk/Bliss-Shader/assets/164027360/95694d48-c8cf-4852-bb96-69b126c61320)

**Comment by dudialqinawi** [comment]
i have the same issue

**Comment by X0nk** [comment]
this is a known issue im working to fix

**Comment by alexmoerschbacher** [comment]
Looks like it is fixed on the newest version. I'm no longer seeing the issue. Thank you!

**Comment by X0nk** [comment]
yes.
iris made a permanent change to the gbuffer program it renders at, to where the lightmap coordinates are always 1.0 (they are usually a gradient 1.0-0.0). that caused it to be full brightness wherever it was.

i had to reimplement it completely. i have done it closer to how mojang did it this time though, so it got upgraded.

**Comment by seanhouli** [comment]
thank you x0nk, as a swe myself (though don't know much about graphics) that sounds like a PITA. upgraded to latest and the fix is great!

**Comment by Veluz22** [comment]
Its happening to me again on 21.1

**Comment by X0nk** [comment]
if you are using v2.0.4 or older on the latest iris versions, it will always happen. use the in-development version if you want to have it fixed
