### ISSUE TITLE
Clouds noise jerk while day translation

### ISSUE THREAD

**Issue by MaksymReshetnikov** [X0nk/Bliss-Shader#78]
![BUG](https://github.com/X0nk/Bliss-Shader/assets/52925689/dfd387d4-2f40-472d-9fea-4bbd9e7d765d)
![BUG_2](https://github.com/X0nk/Bliss-Shader/assets/52925689/89207798-c390-4f95-a02b-9065cf97692e)
Problem: 
Movements timer on noise texture for clouds noise does not take into account the change of days as such, but only the time of day.

(In volumetricClouds.glsl)
float cloud_movement = (worldTime / 24.0) * Cloud_Speed;

Maybe fix:
float cloud_movement = ((float(worldDay)*24000.0 + worldTime) / 24.0) * Cloud_Speed;
Bonus with this fix - "unic" noise texture for cloud in differents days

**Comment by X0nk** [comment]
good idea. clouds are in the middle of being developed (daily weather system is half done atm)
so barely any thought went into the movement.
