### ISSUE TITLE
Seeing lines when using spyglass at the morning

### ISSUE THREAD

**Issue by WhoAmI4093** [X0nk/Bliss-Shader#79]
![2024-03-21_08 48 54](https://github.com/X0nk/Bliss-Shader/assets/101285045/0e7a4b5c-5314-4863-9f66-cf00f3f4fd91)
![2024-03-21_08 51 30](https://github.com/X0nk/Bliss-Shader/assets/101285045/cd75f833-54b3-40a0-b9b7-29604fa82a43)
![2024-03-21_08 51 55](https://github.com/X0nk/Bliss-Shader/assets/101285045/65318321-82f0-4b15-9b4b-ceabd024ff66)

**Comment by X0nk** [comment]
this is depth buffer imprecision made really visible by the screenspace shadows... i can't just create more precision or anything, so there's nothing much i can really do without biasing the contact shadows... which defeats their purpose
