### ISSUE TITLE
No SSGI in Nether/The End

### ISSUE THREAD

**Issue by ShrikerChestTree** [X0nk/Bliss-Shader#8]
When I decided to go into Nether and The End I saw this:
![2023-07-09_01 28 42](https://github.com/X0nk/Bliss-Shader/assets/107254774/624f194e-7eb3-40e3-b491-2c2d60b39123)
![2023-07-09_01 30 17](https://github.com/X0nk/Bliss-Shader/assets/107254774/ce5c1dfe-40ce-4c3f-8244-8a7a51022601)
As far as I understand, these measurements do not include SSGI.
Add them later.

**Comment by X0nk** [comment]
will do.
the nether and end have their own seperated shaders, so i have to make sure to copy paste stuff there too

**Comment by ShrikerChestTree** [comment]
> will do. the nether and end have their own seperated shaders, so i have to make sure to copy paste stuff there too

Thank you!

**Comment by X0nk** [comment]
i have added these features to both dimensions now, after redoing them a bit in the overworld.
