### ISSUE TITLE
DH with minecraft 1.19.4

### ISSUE THREAD

**Issue by TitanGames-729** [X0nk/Bliss-Shader#80]
Hello! I am wondering if there will be support for distant horizons on minecraft 1.19.4. 

It does not render any lods even with the latest dev version.

I asked iris shaders team on github and they said that it only depends on the shader devs.

It would be absolutely amazing to see DH working with shaders on 1.19.4 as not anyone can move their server to 1.20

**Comment by X0nk** [comment]
there is no beta versions of iris and distant horizons that support shaders the same for 1.19.4. only 1.20.4 and 1.20.1
