### ISSUE TITLE
The clouds are transparends when you over them

### ISSUE THREAD

**Issue by Mrgaton** [X0nk/Bliss-Shader#88]

**Comment by Mrgaton** [comment]
![image](https://github.com/X0nk/Bliss-Shader/assets/68958481/97f824ef-c2bb-4b5e-a7f4-4ed8e276bb9b)

**Comment by Mrgaton** [comment]
![image](https://github.com/X0nk/Bliss-Shader/assets/68958481/20fd6600-8acb-4a6f-adb1-68794da15cef)

and also extreme dense shadows where you cant realy see nothing

**Comment by Mrgaton** [comment]
or  when you are down the structure extreme weird effect

![image](https://github.com/X0nk/Bliss-Shader/assets/68958481/d2ca5d57-c700-4bb5-b457-78684ab4a5c8)

**Comment by X0nk** [comment]
1: clouds can be rendered in front, if you enable the "render clouds in front of world" misc settings

2: thats vanilla Minecraft behavior, the flying island will make it darker below it.

3: that is cave fog. i cannot accurately tell when or where a cave is, so unfortunately this is  a scenario where it does not work the best.i olan to improve this a little at some point. you can disable cave fog in the fog settings.

**Comment by Mrgaton** [comment]
And some times everything i so black that i cant se absolutely 0 how i can increase that light at least like vanilla

**Comment by Mrgaton** [comment]
Ok i just changed ambient light
