### ISSUE TITLE
When viewd in 3rd person, enchanted items with PBR are seethrough

### ISSUE THREAD

**Issue by SpiritusKitsune** [X0nk/Bliss-Shader#92]
![2024-04-02_11 25 10](https://github.com/X0nk/Bliss-Shader/assets/165626758/1970159c-b395-40af-88fc-b1ad293852ef)
![2024-04-02_11 25 35](https://github.com/X0nk/Bliss-Shader/assets/165626758/d50526d8-6d4d-4af6-800c-7c030affe64b)

**Comment by X0nk** [comment]
this is a duplicate report of [issue #66](https://github.com/X0nk/Bliss-Shader/issues/66)
