### ISSUE TITLE
Shader not loading

### ISSUE THREAD

**Issue by denissteinhorst** [X0nk/Bliss-Shader#93]
Machine :
MacBook Pro M3 Max 16/40/16 128GB
MacOS Sonoma 14.4.1

Version :
Prism launcher 8.0
Minecraft 1.20.4

Mods :
DistantHorizons-fabric-2.0.2-a-dev-1.20.4.jar
fabric-api-0.96.11+1.20.4.jar
indium-1.0.30+mc1.20.4.jar
iris-1.7.0-snapshot+mc1.20.4-dfec34-dirty.jar
sodium-fabric-0.5.8+mc1.20.4.jar

Error log:
(removed shaders, cleared the log, switched to bliss and copied the whole output)
[https://pastebin.com/JhFjRYPv](https://pastebin.com/JhFjRYPv)

**Comment by X0nk** [comment]
repeat of [issue #64](https://github.com/X0nk/Bliss-Shader/issues/64)
