### ISSUE TITLE
[Linux + RADV] Blue glows and artifacts in certain situations

### ISSUE THREAD

**Issue by GalacticalEdge** [X0nk/Bliss-Shader#95]
![2024-04-02_19 57 07](https://github.com/X0nk/Bliss-Shader/assets/31458662/fa448776-ee89-46fd-8095-9c7ad87f177a)
![2024-04-02_19 57 30](https://github.com/X0nk/Bliss-Shader/assets/31458662/bc7275d1-9f9a-4fec-8de5-a033a98bea51)

I have an issue on my two Linux machines (one using an RX 6600 XT and the other is a Steam Deck) where blue artifacts appear on the player's hand (such as when mining, going into water, a skeleton is behind the hand, etc.)

**Comment by X0nk** [comment]
will look into it.
could you also make sure no mod is conflict and causing it?

**Comment by GalacticalEdge** [comment]
![2024-04-06_11 51 00](https://github.com/X0nk/Bliss-Shader/assets/31458662/965fa806-8f88-42db-9186-bdfeafb81e16)

Here is another rendering artifact I captured under Linux + AMD RADV

**Comment by GalacticalEdge** [comment]
![2024-04-07_16 39 14](https://github.com/X0nk/Bliss-Shader/assets/31458662/6281a181-b490-4bd0-9f08-12a0ee55646d)

Another graphical bug I caught where enchanted items appear semi-transparent

**Comment by X0nk** [comment]
enchant glint being broken in multiple ways is known.

the thing where banners and other translucent things don't get obscured by water from when viewing from outside, is a technical problem, much less a bug. it's one of those things with deferred rendering and translucents... unsure if the technical problem will be solved anytime.

**Comment by GalacticalEdge** [comment]
> enchant glint being broken in multiple ways is known.
> 
> the thing where banners and other translucent things don't get obscured by water from when viewing from outside, is a technical problem, much less a bug. it's one of those things with deferred rendering and translucents... unsure if the technical problem will be solved anytime.

Are you suggesting that the banners and translucent things are most likely a graphics driver-related issue?

**Comment by X0nk** [comment]
no. there is nothing wrong with your device.

it's a technical problem for the design of the shader itself.

**Comment by GalacticalEdge** [comment]
> no. there is nothing wrong with your device.
> 
> it's a technical problem for the design of the shader itself. it's not something easily solvable.

By any chance, does this also occur under Windows with AMD?

**Comment by X0nk** [comment]
as i said, it a problem in the design of the shader, it will happen equally for everyone on every device.

**Comment by dupontinquiries** [comment]
> ![2024-04-07_16 39 14](https://private-user-images.githubusercontent.com/31458662/320322746-6281a181-b490-4bd0-9f08-12a0ee55646d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0OTYzMjEsIm5iZiI6MTcxNDQ5NjAyMSwicGF0aCI6Ii8zMTQ1ODY2Mi8zMjAzMjI3NDYtNjI4MWExODEtYjQ5MC00YmQwLTlmMDgtMTJhMGVlNTU2NDZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDE2NTM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkYWQ0Y2IxNzc4MGVjMWE1ODFmNDVlZGVjMTE2ZjJkODNjYjJhMWFmMDgyYWJmY2VhZmQyNDM1Yzk3ZWI2ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2JsjJh3nOIWtpaR4RuUE_jbPqRPJ4hIdXdvejQDQ5-g)
> 
> Another graphical bug I caught where enchanted items appear semi-transparent

ngl that does look kinda cool... maybe that can be a toggle in the future?

**Comment by Absolute-Potato** [comment]
![2024-05-27_16 00 03](https://github.com/X0nk/Bliss-Shader/assets/29511823/23dbbadc-9ced-4e4a-ab1f-b63be9f4407c)
![2024-05-27_15 59 56](https://github.com/X0nk/Bliss-Shader/assets/29511823/a8fae50c-ca14-4105-bdc5-f7e250b7a24b)
![2024-05-27_15 59 35](https://github.com/X0nk/Bliss-Shader/assets/29511823/878427f6-18d4-4f22-a9fb-8d857bb8fe56)
Any entity behind a transparent material glows bright blue for me. Running Linux (KDE Neon, Mesa drivers) with a 6700XT.

**Comment by X0nk** [comment]
this is [issue#123](https://github.com/X0nk/Bliss-Shader/issues/123), which should be resolved now, please refer to that issue thread for more info
